image: node:20-alpine

stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/
    - .next/cache/

build_job:
  stage: build
  script:
    - npm ci --prefer-offline
    - npx prisma generate
    - npx next build
  only:
    - main
    - merge_requests
