import { HIGH_INTENT_POSTS } from "./high-intent-posts";

export type PostCategory = "BEAUTY" | "SKINCARE" | "HAIR" | "WELLNESS" | "LIFESTYLE" | "MAKEUP";

export type Post = {
 category: PostCategory;
 title: string;
 excerpt: string;
 slug: string;
 readTime: string;
 date: string;
 productCount: number;
 thumbnail: string;
 tags: string[];
};

const STATIC_POSTS: Post[] = [
 {
 category: "WELLNESS",
 title: "Is Your Workout Causing 'Cortisol Face'? The Low-Impact Shift",
 excerpt: "High-intensity cardio raises cortisol, causing puffiness, water retention, and hormonal acne. Explore why low-impact pilates is the secret to aesthetic and cellular longevity.",
 slug: "workout-causing-cortisol-face",
 readTime: "8 min",
 date: "June 2026",
 productCount: 2,
 thumbnail: "CF",
 tags: ["cortisol face", "workout swelling", "low impact fitness", "pilates benefits", "stress hormones", "skincare wellness"],
 },
 {
 category: "SKINCARE",
 title: "The Gym Bag Skincare Guide: How to Sweat Without Clogged Pores",
 excerpt: "Working out is great for circulation, but sweat combined with public gym equipment can trigger painful acne mechanica. Here is your dermatologist-backed pre- and post-workout skin defense routine.",
 slug: "gym-bag-skincare-guide",
 readTime: "6 min",
 date: "June 2026",
 productCount: 1,
 thumbnail: "GB",
 tags: ["gym acne", "workout skincare", "acne mechanica", "hypochlorous acid", "post workout routine", "clear skin tips"],
 },
 {
 category: "LIFESTYLE",
 title: "Why Posture is the Ultimate Wealth Signifier (And How to Fix the Desk Slouch)",
 excerpt: "You can have a premium skincare routine, but a slouched posture instantly ruins the silhouette of looking put-together. Discover the postural biomechanics of elegance and the tools to fix desk-neck.",
 slug: "posture-ultimate-wealth-signifier",
 readTime: "7 min",
 date: "June 2026",
 productCount: 1,
 thumbnail: "PE",
 tags: ["postural elegance", "desk neck fix", "thoracic spine", "back alignment", "ergonomics", "quiet luxury style"],
 },
 {
 category: "LIFESTYLE",
 title: "Why Rich Women Have Better Skin (And It's Not The Products)",
 excerpt: "It's not La Mer. It's sleep, stress management, consistent preventative care, and time — the four things money actually buys when it comes to your complexion.",
 slug: "why-rich-women-have-better-skin",
 readTime: "8 min",
 date: "June 2026",
 productCount: 3,
 thumbnail: "RW",
 tags: ["wealth and skin", "sleep skincare", "stress cortisol skin", "preventative skincare", "lifestyle skincare", "skin inequality"],
 },
 {
 category: "LIFESTYLE",
 title: "The Economics of Looking Expensive",
 excerpt: "Breaking down exactly what makes someone look expensive — and it's rarely what you think. Hair texture, teeth alignment, skin clarity, clothing fit, and posture decoded.",
 slug: "economics-of-looking-expensive",
 readTime: "9 min",
 date: "June 2026",
 productCount: 4,
 thumbnail: "EL",
 tags: ["looking expensive", "grooming investment", "hair skin teeth", "appearance economics", "style", "beauty ROI"],
 },
 {
 category: "SKINCARE",
 title: "What 10 Years of Sun Damage Looks Like on Indian Skin",
 excerpt: "Drivers, founders, office workers, outdoor labourers — a visual and scientific breakdown of what cumulative UV exposure does to Indian skin across a decade, and how to reverse it.",
 slug: "10-years-sun-damage-indian-skin",
 readTime: "10 min",
 date: "June 2026",
 productCount: 4,
 thumbnail: "SD",
 tags: ["sun damage", "UV aging", "hyperpigmentation", "photoaging indian skin", "sunscreen", "melasma", "long term skincare"],
 },
 {
 category: "LIFESTYLE",
 title: "The Hidden Cost of Being Pretty",
 excerpt: "Salon visits, skincare stacks, makeup, waxing, threading, hair colour — an honest breakdown of what Indian women actually spend annually to maintain their appearance, and whether it's worth it.",
 slug: "hidden-cost-of-being-pretty",
 readTime: "7 min",
 date: "June 2026",
 productCount: 2,
 thumbnail: "HC",
 tags: ["beauty cost india", "grooming budget", "beauty tax", "salon expenses", "skincare spend", "cost of beauty"],
 },
 {
 category: "WELLNESS",
 title: "The Founder Face: What Startup Stress Does to Your Appearance",
 excerpt: "Poor sleep, elevated cortisol, blue light exposure, skipped meals, constant travel — a science-backed breakdown of how the founder lifestyle accelerates visible aging and what to do about it.",
 slug: "the-founder-face",
 readTime: "9 min",
 date: "June 2026",
 productCount: 3,
 thumbnail: "FF",
 tags: ["founder wellness", "startup stress skin", "cortisol aging", "blue light aging", "sleep deprivation skin", "entrepreneur appearance", "stress and beauty"],
 },

 {
 category: "SKINCARE",
 title: "Why Is My Face Darker Than My Body? Causes & Treatment",
 excerpt: "Wondering why your face appears darker than your neck or body? Discover the real reasons behind facial hyperpigmentation in Indian skin and how to fix it.",
 slug: "why-is-my-face-darker-than-my-body",
 readTime: "7 min",
 date: "June 2026",
 productCount: 2,
 thumbnail: "DK",
 tags: ["hyperpigmentation", "tanning", "indian skin", "sunscreen", "niacinamide", "melasma", "uneven skin tone"],
 },
 {
 category: "SKINCARE",
 title: "The Ultimate Guide to Pregnancy-Safe Skincare: What to Use & What to Avoid",
 excerpt: "Navigating skincare during pregnancy can be terrifying. A careful, science-backed guide on which ingredients to strictly avoid, and how to safely treat hormonal acne and melasma.",
 slug: "pregnancy-safe-skincare-guide",
 readTime: "9 min",
 date: "June 2026",
 productCount: 0,
 thumbnail: "PR",
 tags: ["pregnancy", "maternity", "safe skincare", "melasma", "retinol alternatives", "hormonal acne"],
 },
 {
 category: "LIFESTYLE",
 title: "Aesthetic Amazon Home Upgrades Under ₹1500 That Feel Expensive",
 excerpt: "From amber glass dispensers to linen organization. Tiny home upgrades that instantly elevate your space on a budget, carefully curated from Amazon India.",
 slug: "amazon-home-upgrades-under-1500",
 readTime: "6 min",
 date: "June 2026",
 productCount: 4,
 thumbnail: "AM",
 tags: ["amazon finds", "home decor", "budget upgrades", "aesthetic home", "organization"],
 },
 {
 category: "LIFESTYLE",
 title: "How to Build a Low-Friction Morning Routine You'll Actually Stick To",
 excerpt: "Stop trying to wake up at 5 AM. Here is a realistic, low-friction approach to mornings that doesn't rely on willpower or extreme discipline.",
 slug: "low-friction-morning-routine",
 readTime: "8 min",
 date: "May 2026",
 productCount: 0,
 thumbnail: "MR",
 tags: ["morning routine", "habits", "productivity", "low friction", "wellness"],
 },
 {
 category: "WELLNESS",
 title: "The Science of the 'Glow': How Intimacy Affects Your Skin and Mind",
 excerpt: "Beyond serums and exfoliants. The real science behind oxytocin, cortisol reduction, and why sexual wellness might be the missing piece to clear skin and a sharp mind.",
 slug: "science-of-the-glow-intimacy-and-skin",
 readTime: "6 min",
 date: "June 2026",
 productCount: 0,
 thumbnail: "GL",
 tags: ["intimacy", "wellness", "cortisol", "hormonal acne", "skin glow", "mental clarity"],
 },
 {
 category: "LIFESTYLE",
 title: "The Art of the Evening Wind-Down: Upgrading Your Night Routine",
 excerpt: "Why your morning routine actually starts at 9 PM the night before. Small, aesthetic upgrades to your evening environment to improve sleep quality.",
 slug: "evening-wind-down-routine",
 readTime: "7 min",
 date: "May 2026",
 productCount: 0,
 thumbnail: "WD",
 tags: ["night routine", "sleep", "wellness", "aesthetic", "habits"],
 },
 {
 category: "BEAUTY",
 title: "Why Your Korean Skincare Routine Is Breaking You Out in India",
 excerpt: "The climate mismatch between Seoul and Mumbai, and why the viral 10-step glass skin routine requires a different approach for Indian skin types.",
 slug: "why-korean-skincare-fails-indian-skin",
 readTime: "8 min",
 date: "June 2026",
 productCount: 3,
 thumbnail: "KS",
 tags: ["korean skincare", "glass skin", "oily skin", "indian climate", "closed comedones", "kbeauty"],
 },
 {
 category: "WELLNESS",
 title: "Wellness for Builders: How Founders Quiet Their Nervous System",
 excerpt: "Startup burnout isn't a mindset problem. It's a nervous system problem. A practical guide to sleep, cortisol, and micro habits for founders, developers, and high-output builders.",
 slug: "wellness-for-builders",
 readTime: "9 min",
 date: "May 2026",
 productCount: 0,
 thumbnail: "WB",
 tags: ["founder wellness", "startup burnout", "nervous system", "mental recovery", "high-output people", "cortisol", "sleep optimization", "focus rituals", "indie hacker wellness", "developer health", "building without burnout"],
 },
 {
 category: "WELLNESS",
 title: "Your Brain Wasn't Built for Infinite Scroll",
 excerpt: "Dopamine loops, notification fatigue, AI overload — how modern apps are quietly hijacking your attention, and a 5-step digital reset to take it back.",
 slug: "your-brain-wasnt-built-for-infinite-scroll",
 readTime: "8 min",
 date: "May 2026",
 productCount: 0,
 thumbnail: "IS",
 tags: ["digital wellness", "dopamine detox", "screen fatigue", "focus recovery", "AI burnout", "infinite scroll", "notification fatigue", "cognitive debt", "digital reset"],
 },
 {
 category: "BEAUTY",
 title: "Why Your Skincare Routine Stops Working in Indian Summer",
 excerpt: "Your routine did not change. Your environment did. A science-backed breakdown of why products behave differently in India's heat and humidity — and exactly what to switch.",
 slug: "why-skincare-routine-stops-working-indian-summer",
 readTime: "11 min",
 date: "May 2026",
 productCount: 7,
 thumbnail: "SU",
 tags: ["summer", "indian climate", "routine fail", "sunscreen", "moisturiser"],
 },
 {
 category: "SKINCARE",
 title: "How to Repair a Damaged Skin Barrier — The 4-Week Protocol for Indian Skin",
 excerpt: "Burning from products that never used to sting. Oily and dry at the same time. Constant breakouts. This is barrier damage — and here is how to fix it.",
 slug: "damaged-skin-barrier-repair",
 readTime: "10 min",
 date: "May 2026",
 productCount: 4,
 thumbnail: "BR",
 tags: ["barrier repair", "sensitive skin", "ceramides", "dry skin", "stinging"],
 },
 {
 category: "SKINCARE",
 title: "Non-Comedogenic Sunscreen That Doesn't Sweat Off in Mumbai Humidity",
 excerpt: "The honest guide to finding a sunscreen that works for oily, acne-prone Indian skin. Lightweight formulas, no white cast, no noon grease.",
 slug: "best-sunscreen-oily-skin-india",
 readTime: "8 min",
 date: "May 2024",
 productCount: 5,
 thumbnail: "OS",
 tags: ["sunscreen", "oily skin", "spf", "acne prone", "minimalist", "aqualogica", "neutrogena"],
 },
 {
 category: "SKINCARE",
 title: "Dark Circles Treatment for Indian Skin — What Actually Works",
 excerpt: "The honest guide to treating dark circles in India. Caffeine + EGCG for puffiness, what to use for pigmentation, and why most eye creams do nothing.",
 slug: "dark-circles-treatment-india",
 readTime: "10 min",
 date: "May 2026",
 productCount: 2,
 thumbnail: "DC",
 tags: ["dark circles", "eye cream", "caffeine", "pigmentation", "puffiness", "eye care"],
 },
 {
 category: "SKINCARE",
 title: "How to Treat Active Acne Fast — Pimple Patches + Benzoyl Peroxide",
 excerpt: "A real protocol for active acne in India. Mighty Patch for overnight spot treatment, benzoyl peroxide for persistent breakouts.",
 slug: "active-acne-treatment-india",
 readTime: "9 min",
 date: "May 2026",
 productCount: 2,
 thumbnail: "AA",
 tags: ["acne", "pimple patches", "benzoyl peroxide", "spot treatment"],
 },
 
 {
 category: "SKINCARE",
 title: "The Indian Pigmentation Playbook (Dermat-Backed Guide)",
 excerpt: "A complete guide to treating pigmentation in Indian skin using the right actives and routines.",
 slug: "pigmentation-guide",
 readTime: "12 min",
 date: "April 2026",
 productCount: 8,
 thumbnail: "PI",
 tags: ["pigmentation", "dark spots", "melasma", "vitamin c", "sunscreen", "indian skin"],
 },
 {
 title:
 "Best Concealers for Indian Skin: Dark Circles, Acne Marks and Pigmentation",
 excerpt:
 "How to choose concealer for Indian undertones, humid weather, dark circles and acne marks without going grey.",
 slug: "best-concealers-indian-skin-dark-circles-acne-marks",
 category: "MAKEUP",
 readTime: "8 min",
 date: "April 2026",
 productCount: 5,
 thumbnail: "CC",
 tags: ["concealer", "dark circles", "acne marks"],
 },
 {
 title: "Beginner Makeup Kit in India Under Rs 2000",
 excerpt:
 "A simple starter kit for regular users: concealer, compact, kajal, mascara and lipstick.",
 slug: "beginner-makeup-kit-india-under-2000",
 category: "MAKEUP",
 readTime: "7 min",
 date: "April 2026",
 productCount: 4,
 thumbnail: "MK",
 tags: ["beginner", "makeup kit", "budget"],
 },
 {
 title: "Oily Skin Makeup Routine in India",
 excerpt:
 "A sweat-friendly everyday base routine for oily skin with minimal layers.",
 slug: "oily-skin-makeup-routine-india",
 category: "MAKEUP",
 readTime: "8 min",
 date: "April 2026",
 productCount: 4,
 thumbnail: "OS",
 tags: ["oily skin", "routine", "makeup"],
 },
 
 {
 category: "BEAUTY",
 title: "Why Your Skin Looks Dull Even After Skincare",
 excerpt: "Hard water, wrong layering, and skipping SPF - the real reasons your skin isn't glowing.",
 slug: "why-skin-looks-dull",
 readTime: "10 min",
 date: "April 2026",
 productCount: 6,
 thumbnail: "GL",
 tags: ["dullness", "glow", "hard water", "spf", "layering"],
 },
 {
 category: "BEAUTY",
 title: "The 1000 Skincare Mistakes Costing You 10000",
 excerpt: "The habits that silently ruin your skincare results - and how to fix them.",
 slug: "skincare-mistakes",
 readTime: "9 min",
 date: "April 2026",
 productCount: 5,
 thumbnail: "MI",
 tags: ["mistakes", "barrier damage", "acne", "routine", "beginner"],
 },
 {
 category: "BEAUTY",
 title: "Minimalist Alpha Arbutin vs Re'equil Ultra Matte Gel vs Dot & Key: Skincare Brand Face-Off",
 excerpt: "A real comparison of India's most popular skincare brands - based on results, not hype.",
 slug: "brand-comparison-india",
 readTime: "11 min",
 date: "April 2026",
 productCount: 7,
 thumbnail: "VS",
 tags: ["minimalist", "the ordinary", "dot and key", "comparison", "niacinamide", "vitamin c"],
 },
 {
 category: "HAIR",
 title: "How to Repair Skin Barrier and Hair Fall from Hard Water in Bangalore",
 excerpt: "The hidden cause of hair fall in Indian cities - and the exact protocol to fix it.",
 slug: "hard-water-hair",
 readTime: "11 min",
 date: "April 2026",
 productCount: 8,
 thumbnail: "HW",
 tags: ["hair fall", "hard water", "shampoo", "scalp", "india"],
 },
 {
 category: "BEAUTY",
 title: "The 12 Skincare Products That Actually Changed My Skin",
 excerpt: "After years of testing everything, these are the only products still on my shelf.",
 slug: "skincare-products-that-changed-my-skin",
 readTime: "8 min",
 date: "March 2026",
 productCount: 12,
 thumbnail: "PR",
 tags: ["best products", "skincare", "routine", "review"],
 },
 {
 category: "WELLNESS",
 title: "Morning Routines That Don't Require 2 Hours",
 excerpt: "Five things. Twenty minutes. A real difference.",
 slug: "morning-routines",
 readTime: "5 min",
 date: "March 2026",
 productCount: 5,
 thumbnail: "AM",
 tags: ["morning routine", "wellness", "habits"],
 },
 {
 category: "BEAUTY",
 title: "Amazon Skincare Finds Under 1500 That Dermatologists Actually Use",
 excerpt: "Budget doesn't mean compromise. These prove it.",
 slug: "amazon-skincare-under-1500",
 readTime: "6 min",
 date: "March 2026",
 productCount: 8,
 thumbnail: "BU",
 tags: ["amazon", "under 1500", "budget", "skincare", "dermatologist"],
 },
 {
 category: "LIFESTYLE",
 title: "Gift Guides for the Woman Who Has Everything",
 excerpt: "She's impossible to shop for. We figured it out.",
 slug: "gift-guide-woman-who-has-everything",
 readTime: "7 min",
 date: "Feb 2026",
 productCount: 15,
 thumbnail: "GI",
 tags: ["gift guide", "lifestyle", "amazon"],
 },
 {
 category: "WELLNESS",
 title: "The Supplements Worth Taking (And the Ones That Are Just Hype)",
 excerpt: "Honest breakdown. No sponsorships. Just research.",
 slug: "supplements-worth-taking",
 readTime: "9 min",
 date: "Feb 2026",
 productCount: 10,
 thumbnail: "SU",
 tags: ["supplements", "wellness", "ashwagandha", "research"],
 },
 {
 category: "BEAUTY",
 title: "The Right Order to Apply Your Skincare (Most People Get This Wrong)",
 excerpt: "Layering matters. This is the sequence that actually works.",
 slug: "skincare-layering-order",
 readTime: "5 min",
 date: "Jan 2026",
 productCount: 6,
 thumbnail: "OR",
 tags: ["layering", "routine order", "cleanser", "serum", "moisturiser", "sunscreen"],
 },
 {
 category: "LIFESTYLE",
 title: "The 8 Amazon Buys That Changed How I Live at Home",
 excerpt: "Small upgrades. Massive difference to daily life.",
 slug: "amazon-home-buys",
 readTime: "6 min",
 date: "Jan 2026",
 productCount: 8,
 thumbnail: "HO",
 tags: ["amazon", "home", "lifestyle"],
 },
 {
 category: "BEAUTY",
 title: "Best Sunscreens in India (2026) That Actually Work",
 excerpt: "No white cast. No greasy finish. Just sunscreens that people actually use daily.",
 slug: "best-sunscreens-india-2026",
 readTime: "5 min",
 date: "March 2026",
 productCount: 9,
 thumbnail: "SP",
 tags: ["sunscreen", "spf 50", "no white cast", "oily skin", "india"],
 },
 {
 category: "BEAUTY",
 title: "4-Step Indian Skincare Routine Under 2000 (That Actually Works)",
 excerpt: "A simple, no-fluff routine built for Indian skin, weather, and budgets.",
 slug: "budget-skincare-routine-under-2000",
 readTime: "9 min",
 date: "April 2026",
 productCount: 9,
 thumbnail: "RT",
 tags: ["routine", "under 2000", "budget", "indian skin", "beginner"],
 },
 {
 category: "BEAUTY",
 title: "Niacinamide 5% vs 10% - Which One Does Your Skin Actually Need?",
 excerpt: "The honest breakdown of what each concentration does differently - and which one is right for your skin type.",
 slug: "niacinamide-5-vs-10",
 readTime: "8 min",
 date: "April 2026",
 productCount: 3,
 thumbnail: "N5",
 tags: ["niacinamide", "5%", "10%", "oily skin", "acne marks"],
 },
 {
 category: "BEAUTY",
 title: "Niacinamide vs Vitamin C - Which One Does Indian Skin Actually Need?",
 excerpt: "What each ingredient does, which concerns they target, and how to layer them correctly in Indian weather.",
 slug: "niacinamide-vs-vitamin-c",
 readTime: "9 min",
 date: "April 2026",
 productCount: 3,
 thumbnail: "NC",
 tags: ["niacinamide", "vitamin c", "pigmentation", "acne marks", "layering"],
 },
 {
 category: "BEAUTY",
 title: "Niacinamide for Oily Skin in India - How It Actually Controls Oil",
 excerpt: "Why niacinamide works for oily skin in Indian humidity, what concentration to use, and the full AM/PM routine.",
 slug: "niacinamide-for-oily-skin",
 readTime: "10 min",
 date: "April 2026",
 productCount: 4,
 thumbnail: "OI",
 tags: ["niacinamide", "oily skin", "oil control", "pores", "india"],
 },
 {
 category: "BEAUTY",
 title: "Sunscreen in India - Why SPF 50 Is Non-Negotiable",
 excerpt: "Why Indian skin needs SPF 50+ and the best options available.",
 slug: "best-sunscreen-india-spf50",
 readTime: "11 min",
 date: "April 2026",
 productCount: 5,
 thumbnail: "50",
 tags: ["sunscreen", "spf 50", "pigmentation", "uv", "india"],
 },
 {
 category: "BEAUTY",
 title: "Serums vs Essences vs Moisturisers - What You Actually Need",
 excerpt: "The honest breakdown of what each product does and what your skin actually needs.",
 slug: "serums-essences-moisturizers-guide",
 readTime: "10 min",
 date: "April 2026",
 productCount: 6,
 thumbnail: "SE",
 tags: ["serum", "essence", "moisturiser", "routine", "hydration"],
 },
 {
 category: "SKINCARE",
 title: "Complete Skincare Routine for Every Skin Type",
 excerpt: "A science-backed 4-step routine for oily, dry, combination, and sensitive skin.",
 slug: "skincare-routine-every-skin-type",
 readTime: "14 min",
 date: "April 2026",
 productCount: 12,
 thumbnail: "RS",
 tags: ["routine", "oily skin", "dry skin", "combination skin", "sensitive skin", "beginner"],
 },
 {
 category: "SKINCARE",
 title: "Best Beginner Skincare Routine for India (2026) — 3 Products, Real Results",
 excerpt: "You do not need 10 steps. You need 3 right products used consistently. The complete beginner skincare routine for Indian skin — cleanser, moisturiser, sunscreen.",
 slug: "beginner-skincare-routine-india",
 readTime: "12 min",
 date: "May 2026",
 productCount: 10,
 thumbnail: "BR",
 tags: ["beginner", "routine", "cleanser", "moisturiser", "sunscreen", "budget", "under 1500"],
 },
 {
 category: "SKINCARE",
 title: "Everything Indian Humidity Does to Your Skin (And How to Fix It)",
 excerpt: "Why Western skincare fails in Indian humidity — and what actually works. Covers sweating, clogged pores, fungal acne, hard water, sunscreen texture, and the right AM/PM routine for humid Indian weather.",
 slug: "humidity-skincare-india",
 readTime: "13 min",
 date: "May 2026",
 productCount: 6,
 thumbnail: "HU",
 tags: ["skincare for Indian humidity", "humidity skin problems India", "best moisturiser humid weather", "fungal acne India", "monsoon skincare", "oily skin Mumbai", "Indian climate skincare routine", "sweaty skin routine India"],
 },
 {
 category: "WELLNESS",
 title: "The Indian Girl's Night Routine That Actually Improves Sleep",
 excerpt: "A realistic Indian girl's night routine for better sleep — magnesium glycinate, low-light habits, shower timing, skincare that doesn't feel like a second job. No 5am alarm required.",
 slug: "indian-night-routine-better-sleep",
 readTime: "11 min",
 date: "May 2026",
 productCount: 4,
 thumbnail: "SL",
 tags: ["sleep routine India", "night routine Indian skin", "magnesium glycinate sleep", "sleep wellness India", "bedtime routine", "silk pillowcase benefits", "calming tea before bed"],
 },
 {
 category: "SKINCARE",
 title: "Best Moisturisers for Oily vs Dry Skin in India (2026 Guide)",
 excerpt: "Gel, cream, or lotion? The honest breakdown of the best moisturisers for oily, dry, and combination Indian skin — including why your current moisturiser might not be working.",
 slug: "best-moisturisers-india-2026",
 readTime: "11 min",
 date: "April 2026",
 productCount: 2,
 thumbnail: "MO",
 tags: ["moisturiser", "dry skin", "oily skin", "cetaphil", "neutrogena", "indian skin"],
 },
 {
 category: "SKINCARE",
 title: "Best Niacinamide Serums in India (2026) — Ranked by Ingredient Quality",
 excerpt: "A research-backed breakdown of the best niacinamide serums available in India. Ranked by concentration, formulation quality, and real-world performance for Indian skin.",
 slug: "best-niacinamide-serums-india",
 readTime: "12 min",
 date: "April 2026",
 productCount: 6,
 thumbnail: "NS",
 tags: ["niacinamide", "serum", "oil control", "pore minimizer", "minimalist", "the ordinary", "plum", "mamaearth", "deconstruct"],
 },
 {
 category: "BEAUTY",
 title: "Complete Budget Beauty Routine: ₹2,000 That Actually Works",
 excerpt: "The complete budget beauty routine under ₹2,000. 8 products, real results, and a side-by-side comparison of budget vs expensive brands.",
 slug: "budget-beauty-routine-2000",
 readTime: "9 min",
 date: "March 2026",
 productCount: 8,
 thumbnail: "BU",
 tags: ["budget", "skincare routine", "under 2000", "cetaphil", "minimalist", "deconstruct", "mCaffeine", "tresemme"],
 },
 {
 category: "SKINCARE",
 title: "Salicylic Acid for Indian Skin — Acne, Blackheads, Oily Skin (2026)",
 excerpt: "The complete salicylic acid guide for Indian skin. What concentration to use, how to layer it, what to avoid, and the best products available in India by budget.",
 slug: "salicylic-acid-guide-india",
 readTime: "12 min",
 date: "April 2026",
 productCount: 5,
 thumbnail: "SA",
 tags: ["salicylic acid", "bha", "acne", "blackheads", "oily skin", "indian skin"],
 },
 {
 category: "BEAUTY",
 title: "The Complete Skincare Routine for Indian Climate (2026)",
 excerpt: "The exact routine that changed my skin — and how to adapt it for your city. Built for India's humidity, pollution, and temperature swings.",
 slug: "skincare-routine-complete-india",
 readTime: "12 min",
 date: "March 2026",
 productCount: 6,
 thumbnail: "CC",
 tags: ["routine", "indian climate", "humidity", "monsoon", "summer", "cetaphil", "minimalist", "deconstruct"],
 },
 {
  category: "SKINCARE",
  title: "What Niacinamide Actually Does to Your Skin (India Edition)",
  excerpt: "The no-fluff India-specific guide to niacinamide: oil control, open pores, acne marks, skin barrier support, and the best serums under ₹700.",
  slug: "what-niacinamide-does-to-your-skin",
  readTime: "10 min",
  date: "April 2026",
  productCount: 4,
  thumbnail: "NC",
  tags: ["niacinamide", "skin barrier", "pores", "oil control", "acne marks", "serums"],
 },
];

export const POSTS: Post[] = [
  ...STATIC_POSTS,
  ...HIGH_INTENT_POSTS.map(p => ({
    category: p.category,
    title: p.title,
    excerpt: p.excerpt,
    slug: p.slug,
    readTime: p.readTime,
    date: p.date,
    productCount: p.asins.length,
    thumbnail: p.thumbnail,
    tags: p.tags
  }))
];

const hashString = (str: string) => {
 let hash = 0;
 for (let i = 0; i < str.length; i++) {
 hash = (hash << 5) - hash + str.charCodeAt(i);
 hash |= 0;
 }
 return Math.abs(hash);
};

// Complete slug → unique image lookup table (all 34 available images used)
const SLUG_IMAGE_MAP: Record<string, string> = {
 // NEW PREMIUM EDITORIAL SERIES — June 2026
 "workout-causing-cortisol-face": "/blog-thumbs/wellness.png",
 "gym-bag-skincare-guide": "/blog-thumbs/skincare_2.png",
 "posture-ultimate-wealth-signifier": "/blog-thumbs/lifestyle.png",
 "why-rich-women-have-better-skin": "/blog-thumbs/blog_rich_women_skin.png",
 "economics-of-looking-expensive": "/blog-thumbs/blog_economics_expensive.png",
 "10-years-sun-damage-indian-skin": "/blog-thumbs/blog_sun_damage.png",
 "hidden-cost-of-being-pretty": "/blog-thumbs/photo_beauty.png",
 "the-founder-face": "/blog-thumbs/blog_founder_wellness.png",

 // SKINCARE — 17 posts
 "why-is-my-face-darker-than-my-body": "/blog-thumbs/blog_face_darker.png",
 "pregnancy-safe-skincare-guide": "/blog-thumbs/blog_pregnancy_safe.png",
 "damaged-skin-barrier-repair": "/blog-thumbs/blog_barrier_repair.png",
 "best-sunscreen-oily-skin-india": "/blog-thumbs/skincare_2.png",
 "dark-circles-treatment-india": "/blog-thumbs/blog_dark_circles.png",
 "active-acne-treatment-india": "/blog-thumbs/blog_salicylic.png",
 "pigmentation-guide": "/blog-thumbs/skincare.png",
 "best-concealers-indian-skin-dark-circles-acne-marks": "/blog-thumbs/blog_makeup_kit.png",
 "beginner-makeup-kit-india-under-2000": "/blog-thumbs/photo_makeup.png",
 "oily-skin-makeup-routine-india": "/blog-thumbs/beauty.png",
 "skincare-routine-every-skin-type": "/blog-thumbs/photo_girl.png",
 "beginner-skincare-routine-india": "/blog-thumbs/beginner_skincare_routine.png",
 "humidity-skincare-india": "/blog-thumbs/photo_korean.png",
 "best-moisturisers-india-2026": "/blog-thumbs/wellness.png",
 "best-niacinamide-serums-india": "/blog-thumbs/blog_niacinamide.png",
 "salicylic-acid-guide-india": "/blog-thumbs/hair.png", // use existing unused
 "what-niacinamide-does-to-your-skin": "/blog-thumbs/skincare_2.png", // pair: both niacinamide posts

 // BEAUTY — 17 posts
 "why-korean-skincare-fails-indian-skin": "/blog-thumbs/blog_korean_mismatch.png",
 "why-skincare-routine-stops-working-indian-summer": "/blog-thumbs/blog_indian_summer.png",
 "why-skin-looks-dull": "/blog-thumbs/blog_intimacy_glow.png",
 "skincare-mistakes": "/blog-thumbs/beauty_2.png",
 "brand-comparison-india": "/blog-thumbs/photo_beauty.png",
 "skincare-products-that-changed-my-skin": "/blog-thumbs/hair_2.png", // use existing unused
 "amazon-skincare-under-1500": "/blog-thumbs/photo_amazon.png",
 "skincare-layering-order": "/blog-thumbs/blog_layering.png",
 "best-sunscreens-india-2026": "/blog-thumbs/photo_shampoo.png",
 "budget-skincare-routine-under-2000": "/blog-thumbs/blog_budget.png",
 "niacinamide-5-vs-10": "/blog-thumbs/blog_niacinamide.png",
 "niacinamide-vs-vitamin-c": "/blog-thumbs/skincare.png",
 "niacinamide-for-oily-skin": "/blog-thumbs/beauty.png",
 "best-sunscreen-india-spf50": "/blog-thumbs/blog_indian_summer.png",
 "serums-essences-moisturizers-guide": "/blog-thumbs/skincare_3.png",
 "budget-beauty-routine-2000": "/blog-thumbs/blog_budget_2000.png",
 "skincare-routine-complete-india": "/blog-thumbs/photo_hair.png", // use existing unused

 // WELLNESS — 6 posts
 "science-of-the-glow-intimacy-and-skin": "/blog-thumbs/blog_intimacy_glow.png",
 "wellness-for-builders": "/blog-thumbs/blog_founder_wellness.png",
 "your-brain-wasnt-built-for-infinite-scroll": "/blog-thumbs/blog_infinite_scroll.png",
 "morning-routines": "/blog-thumbs/blog_morning_routine.png",
 "supplements-worth-taking": "/blog-thumbs/blog_supplements.png",
 "indian-night-routine-better-sleep": "/blog-thumbs/wellness_2.png",

 // LIFESTYLE — 5 posts
 "amazon-home-upgrades-under-1500": "/blog-thumbs/lifestyle.png",
 "low-friction-morning-routine": "/blog-thumbs/blog_morning_routine.png",
 "evening-wind-down-routine": "/blog-thumbs/wellness.png",
 "gift-guide-woman-who-has-everything": "/blog-thumbs/blog_gift_guide.png",
 "amazon-home-buys": "/blog-thumbs/photo_amazon.png",

 // HAIR — 1 post
 "hard-water-hair": "/blog-thumbs/blog_hard_water.png",
};

export const getRelevantImage = (slug: string, _title: string, category: string): string => {
 // Direct slug lookup first — every known post gets a unique image
 if (SLUG_IMAGE_MAP[slug]) return SLUG_IMAGE_MAP[slug];

 // Fallback for any future posts not yet in the map
 const pools = {
 BEAUTY: ["/blog-thumbs/beauty.png", "/blog-thumbs/beauty_2.png", "/blog-thumbs/photo_beauty.png"],
 WELLNESS: ["/blog-thumbs/wellness.png", "/blog-thumbs/wellness_2.png"],
 LIFESTYLE: ["/blog-thumbs/lifestyle.png", "/blog-thumbs/photo_amazon.png"],
 SKINCARE: ["/blog-thumbs/skincare.png", "/blog-thumbs/skincare_2.png", "/blog-thumbs/skincare_3.png"],
 HAIR: ["/blog-thumbs/photo_hair.png", "/blog-thumbs/hair.png", "/blog-thumbs/hair_2.png"],
 MAKEUP: ["/blog-thumbs/photo_makeup.png", "/blog-thumbs/beauty.png"],
 };
 const pool = pools[category as keyof typeof pools] || pools.SKINCARE;
 return pool[hashString(slug) % pool.length];
};


