export type PostCategory = "BEAUTY" | "SKINCARE" | "HAIR" | "WELLNESS" | "LIFESTYLE" | "MAKEUP";

export type Post = {
  category: PostCategory;
  title: string;
  excerpt: string;
  slug: string;
  readTime: string;
  date: string;
  productCount: number;
  thumbnail: string;
  tags: string[];
};

export const POSTS: Post[] = [
  
  {
    category: "SKINCARE",
    title: "The Indian Pigmentation Playbook (Dermat-Backed Guide)",
    excerpt: "A complete guide to treating pigmentation in Indian skin using the right actives and routines.",
    slug: "pigmentation-guide",
    readTime: "12 min",
    date: "April 2026",
    productCount: 8,
    thumbnail: "PI",
    tags: ["pigmentation", "dark spots", "melasma", "vitamin c", "sunscreen", "indian skin"],
  },
    {
    title:
      "Best Concealers for Indian Skin: Dark Circles, Acne Marks and Pigmentation",
    excerpt:
      "How to choose concealer for Indian undertones, humid weather, dark circles and acne marks without going grey.",
    slug: "best-concealers-indian-skin-dark-circles-acne-marks",
    category: "MAKEUP",
    readTime: "8 min",
    date: "April 2026",
    productCount: 5,
    thumbnail: "CC",
    tags: ["concealer", "dark circles", "acne marks"],
  },
  {
    title: "Beginner Makeup Kit in India Under Rs 2000",
    excerpt:
      "A simple starter kit for regular users: concealer, compact, kajal, mascara and lipstick.",
    slug: "beginner-makeup-kit-india-under-2000",
    category: "MAKEUP",
    readTime: "7 min",
    date: "April 2026",
    productCount: 4,
    thumbnail: "MK",
    tags: ["beginner", "makeup kit", "budget"],
  },
  {
    title: "Oily Skin Makeup Routine in India",
    excerpt:
      "A sweat-friendly everyday base routine for oily skin with minimal layers.",
    slug: "oily-skin-makeup-routine-india",
    category: "MAKEUP",
    readTime: "8 min",
    date: "April 2026",
    productCount: 4,
    thumbnail: "OS",
    tags: ["oily skin", "routine", "makeup"],
  },
  {
    title: "Best Sunscreens in India (2026) That Actually Work",
    excerpt: "No white cast. No greasy finish. Just sunscreens people can use daily.",
    slug: "best-sunscreens-india-2026",
    category: "Beauty",
    readTime: "5 min",
    date: "March 2026",
  },
  {
    title: "The Indian Pigmentation Playbook",
    excerpt:
      "How to think about pigmentation, SPF, actives and consistency.",
    slug: "pigmentation-guide",
    category: "SKINCARE",
    readTime: "12 min",
    date: "April 2026",
    productCount: 8,
    thumbnail: "PI",
    tags: ["pigmentation"],
  },
  {
    title: "Complete Skincare Routine for Every Skin Type",
    excerpt:
      "A clear 4-step routine for oily, dry, combination and sensitive skin.",
    slug: "skincare-routine-every-skin-type",
    category: "SKINCARE",
    readTime: "14 min",
    date: "April 2026",
    productCount: 12,
    thumbnail: "RS",
    tags: ["routine"],
  },
  {
    category: "BEAUTY",
    title: "Why Your Skin Looks Dull Even After Skincare",
    excerpt: "Hard water, wrong layering, and skipping SPF - the real reasons your skin isn't glowing.",
    slug: "why-skin-looks-dull",
    readTime: "10 min",
    date: "April 2026",
    productCount: 6,
    thumbnail: "GL",
    tags: ["dullness", "glow", "hard water", "spf", "layering"],
  },
  {
    category: "BEAUTY",
    title: "The 1000 Skincare Mistakes Costing You 10000",
    excerpt: "The habits that silently ruin your skincare results - and how to fix them.",
    slug: "skincare-mistakes",
    readTime: "9 min",
    date: "April 2026",
    productCount: 5,
    thumbnail: "MI",
    tags: ["mistakes", "barrier damage", "acne", "routine", "beginner"],
  },
  {
    category: "BEAUTY",
    title: "Minimalist vs The Ordinary vs Dot & Key - What Actually Works?",
    excerpt: "A real comparison of India's most popular skincare brands - based on results, not hype.",
    slug: "brand-comparison-india",
    readTime: "11 min",
    date: "April 2026",
    productCount: 7,
    thumbnail: "VS",
    tags: ["minimalist", "the ordinary", "dot and key", "comparison", "niacinamide", "vitamin c"],
  },
  {
    category: "HAIR",
    title: "Why Your Hair Won't Stop Falling (Hard Water India Guide)",
    excerpt: "The hidden cause of hair fall in Indian cities - and the exact protocol to fix it.",
    slug: "hard-water-hair",
    readTime: "11 min",
    date: "April 2026",
    productCount: 8,
    thumbnail: "HW",
    tags: ["hair fall", "hard water", "shampoo", "scalp", "india"],
  },
  {
    category: "BEAUTY",
    title: "The 12 Skincare Products That Actually Changed My Skin",
    excerpt: "After years of testing everything, these are the only products still on my shelf.",
    slug: "skincare-products-that-changed-my-skin",
    readTime: "8 min",
    date: "March 2026",
    productCount: 12,
    thumbnail: "PR",
    tags: ["best products", "skincare", "routine", "review"],
  },
  {
    category: "WELLNESS",
    title: "Morning Routines That Don't Require 2 Hours",
    excerpt: "Five things. Twenty minutes. A real difference.",
    slug: "morning-routines",
    readTime: "5 min",
    date: "March 2026",
    productCount: 5,
    thumbnail: "AM",
    tags: ["morning routine", "wellness", "habits"],
  },
  {
    category: "BEAUTY",
    title: "Amazon Skincare Finds Under 1500 That Dermatologists Actually Use",
    excerpt: "Budget doesn't mean compromise. These prove it.",
    slug: "amazon-skincare-under-1500",
    readTime: "6 min",
    date: "March 2026",
    productCount: 8,
    thumbnail: "BU",
    tags: ["amazon", "under 1500", "budget", "skincare", "dermatologist"],
  },
  {
    category: "LIFESTYLE",
    title: "Gift Guides for the Woman Who Has Everything",
    excerpt: "She's impossible to shop for. We figured it out.",
    slug: "gift-guide-woman-who-has-everything",
    readTime: "7 min",
    date: "Feb 2026",
    productCount: 15,
    thumbnail: "GI",
    tags: ["gift guide", "lifestyle", "amazon"],
  },
  {
    category: "WELLNESS",
    title: "The Supplements Worth Taking (And the Ones That Are Just Hype)",
    excerpt: "Honest breakdown. No sponsorships. Just research.",
    slug: "supplements-worth-taking",
    readTime: "9 min",
    date: "Feb 2026",
    productCount: 10,
    thumbnail: "SU",
    tags: ["supplements", "wellness", "ashwagandha", "research"],
  },
  {
    category: "BEAUTY",
    title: "The Right Order to Apply Your Skincare (Most People Get This Wrong)",
    excerpt: "Layering matters. This is the sequence that actually works.",
    slug: "skincare-layering-order",
    readTime: "5 min",
    date: "Jan 2026",
    productCount: 6,
    thumbnail: "OR",
    tags: ["layering", "routine order", "cleanser", "serum", "moisturiser", "sunscreen"],
  },
  {
    category: "LIFESTYLE",
    title: "The 8 Amazon Buys That Changed How I Live at Home",
    excerpt: "Small upgrades. Massive difference to daily life.",
    slug: "amazon-home-buys",
    readTime: "6 min",
    date: "Jan 2026",
    productCount: 8,
    thumbnail: "HO",
    tags: ["amazon", "home", "lifestyle"],
  },
  {
    category: "BEAUTY",
    title: "Best Sunscreens in India (2026) That Actually Work",
    excerpt: "No white cast. No greasy finish. Just sunscreens that people actually use daily.",
    slug: "best-sunscreens-india-2026",
    readTime: "5 min",
    date: "March 2026",
    productCount: 9,
    thumbnail: "SP",
    tags: ["sunscreen", "spf 50", "no white cast", "oily skin", "india"],
  },
  {
    category: "BEAUTY",
    title: "4-Step Indian Skincare Routine Under 2000 (That Actually Works)",
    excerpt: "A simple, no-fluff routine built for Indian skin, weather, and budgets.",
    slug: "budget-skincare-routine-under-2000",
    readTime: "9 min",
    date: "April 2026",
    productCount: 9,
    thumbnail: "RT",
    tags: ["routine", "under 2000", "budget", "indian skin", "beginner"],
  },
  {
    category: "BEAUTY",
    title: "Niacinamide 5% vs 10% - Which One Does Your Skin Actually Need?",
    excerpt: "The honest breakdown of what each concentration does differently - and which one is right for your skin type.",
    slug: "niacinamide-5-vs-10",
    readTime: "8 min",
    date: "April 2026",
    productCount: 3,
    thumbnail: "N5",
    tags: ["niacinamide", "5%", "10%", "oily skin", "acne marks"],
  },
  {
    category: "BEAUTY",
    title: "Niacinamide vs Vitamin C - Which One Does Indian Skin Actually Need?",
    excerpt: "What each ingredient does, which concerns they target, and how to layer them correctly in Indian weather.",
    slug: "niacinamide-vs-vitamin-c",
    readTime: "9 min",
    date: "April 2026",
    productCount: 3,
    thumbnail: "NC",
    tags: ["niacinamide", "vitamin c", "pigmentation", "acne marks", "layering"],
  },
  {
    category: "BEAUTY",
    title: "Niacinamide for Oily Skin in India - How It Actually Controls Oil",
    excerpt: "Why niacinamide works for oily skin in Indian humidity, what concentration to use, and the full AM/PM routine.",
    slug: "niacinamide-for-oily-skin",
    readTime: "10 min",
    date: "April 2026",
    productCount: 4,
    thumbnail: "OI",
    tags: ["niacinamide", "oily skin", "oil control", "pores", "india"],
  },
  {
    category: "BEAUTY",
    title: "Sunscreen in India - Why SPF 50 Is Non-Negotiable",
    excerpt: "Why Indian skin needs SPF 50+ and the best options available.",
    slug: "best-sunscreen-india-spf50",
    readTime: "11 min",
    date: "April 2026",
    productCount: 5,
    thumbnail: "50",
    tags: ["sunscreen", "spf 50", "pigmentation", "uv", "india"],
  },
  {
    category: "BEAUTY",
    title: "Serums vs Essences vs Moisturisers - What You Actually Need",
    excerpt: "The honest breakdown of what each product does and what your skin actually needs.",
    slug: "serums-essences-moisturizers-guide",
    readTime: "10 min",
    date: "April 2026",
    productCount: 6,
    thumbnail: "SE",
    tags: ["serum", "essence", "moisturiser", "routine", "hydration"],
  },
  {
    category: "SKINCARE",
    title: "Complete Skincare Routine for Every Skin Type",
    excerpt: "A science-backed 4-step routine for oily, dry, combination, and sensitive skin.",
    slug: "skincare-routine-every-skin-type",
    readTime: "14 min",
    date: "April 2026",
    productCount: 12,
    thumbnail: "RS",
    tags: ["routine", "oily skin", "dry skin", "combination skin", "sensitive skin", "beginner"],
  },
  
];
