export const PRODUCTS = [
  {
    id: 1,
    name: "Cetaphil Gentle Skin Hydrating Face Wash 118ml",
    brand: "Cetaphil",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 459,
    price: 384,
    rating: 4.5,
    reviews: "1.3L+",
    asin: "B01CCGW4OE",
    badge: "Top Rated",
    description: "Paraben Free, Sulphate-Free Gentle Skin Hydrating Cleanser with Niacinamide, Vitamin B5 for Dry to Normal, Sensitive Skin.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Glycerin",
      "Texture": "Gel",
      "Use": "Daily cleanser"
    },
    tags: ["cleanser", "gentle", "face wash", "cetaphil"],
    image: "/products/cetaphil-facewash.jpg",
  },
  {
    id: 2,
    name: "Simple Kind To Skin Moisturising Facial Wash, 150 ml",
    brand: "Unilever",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 420,
    price: 329,
    rating: 4.2,
    reviews: "5.5k",
    asin: "B00V4R0ET0",
    badge: "Bestseller",
    description: "100% Soap-Free Moisturising Facewash with Panthenol for dry, sensitive skin | Reduces Visual Dryness & Strengthens Skin Barrier.",
    specs: {
      "Skin Type": "Dry, Sensitive",
      "Key Ingredient": "Glycerin",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["Vitamin-E", "Panthenol", "Pro Amino"],
    image: "/products/Simple-Moisturising.jpg",
    link: "https://amzn.to/48nWKaG",
  },
  {
    id: 3,
    name: "Minimalist 7% ALA + Glycolic Brightening Face Wash 100ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 399,
    price: 380,
    rating: 4.2,
    reviews: "3.2k",
    asin: "B09VLDY46B",
    badge: "Trending Now",
    description: "Gentle Exfoliating Cleanser for Glowing Skin & Oil Control, Sulphate Free.",
    specs: {
      "Skin Type": "All, Combination, Dry, Normal, Oily, Sensitive",
      "Key Ingredient": "Glycolic Acid",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["Alpha Lipoic Acid", "Vitamin B5", "face wash"],
    image: "/products/Minimalist-ALA.jpg",
    link: "https://amzn.to/4cn8R9n",
  },
  {
    id: 4,
    name: "Minimalist Sunscreen SPF 50 PA+++ with Niacinamide & Multi-Vitamins 100gm",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 699,
    price: 533,
    rating: 4.1,
    reviews: "31.3k",
    asin: "B0DHY6LQTW",
    badge: "Smart Buy",
    description: "Clinically Tested in US (In-Vivo) | Lightweight with Multi-Vitamins | No White Cast | Broad Spectrum | Face Sunscreen for Men & Women | 100gm.",
    specs: {
      "Skin Type": "All, Combination, Dry, Normal, Oily, Sensitive",
      "Key Ingredient": "Niacinamide, Multi-Vitamins",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA+++", "Niacinamide", "Multi-Vitamins"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Minimalist-Sunscreen.jpg",
    link: "https://amzn.to/4muroFm",
  },
  {
    id: 5,
    name: "Aqualogica Radiance+ Dewy Sunscreen with Watermelon & Niacinamide with SPF 50 & PA++++ - 80g",
    brand: "Aqualogica",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 599,
    price: 388,
    rating: 4.1,
    reviews: "10k",
    asin: "B0C9JPWLR4",
    badge: "Best for Price",
    description: "Broad Spectrum SPF 50+ PA++++ | UVA/B & Blue Light Protection | Anti-Pollution Factor (APF) Technology | In Vivo Tested | Ideal for Oily Skin Type | Fragrance-Free & No White Cast | For Radiant Skin.",
    specs: {
      "Skin Type": "All, Combination, Dry, Normal, Oily, Sensitive",
      "Key Ingredient": "Hyaluronic Acid, Niacinamide, Watermelon",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA++++", "Niacinamide", "Anti-Pollution"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Aqualogica-Radiance.jpg",
    link: "https://amzn.to/3OcJtLm",
  },
  {
    id: 6,
    name: "mCaffeine Exfoliating Coffee Body Scrub Powder Jar 100gm",
    brand: "mCaffeine",
    category: "Body Care",
    subcat: "Body Scrub",
    mrp: 449,
    price: 369,
    rating: 4.3,
    reviews: "27.4k",
    asin: "B07K4BFQK1",
    badge: "Bestseller",
    description: "mCaffeine Exfoliating Coffee Body Scrub Powder Jar for Tan Removal & Soft-Smooth Skin | De-Tan Bathing Scrub With Coconut Oil | Removes Dirt & Dead Skin | All Skin Types.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Coffee, Caffeine, Coconut Oil",
      "Texture": "Powder",
      "Use": "Daily"
    },
    tags: ["exfoliating", "body scrub", "tan removal", "coffee"],
    image: "/products/mCaffeine-Exfoliating.jpg",
    link: "https://amzn.to/4eerGxJ",
  },
  {
    id: 7,
    name: "DOVE Nourishing Bodywash, 825ml",
    brand: "Dove",
    category: "Body Care",
    subcat: "Body Wash",
    mrp: 560,
    price: 302,
    rating: 4.4,
    reviews: "29k",
    asin: "B07S7R626P",
    badge: "Best for Price",
    description: "For Soft and Smooth Skin, with Triple Hydration Serum & Glycerine, Dermatologically Tested, Paraben-Free, Sulphate-Free.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Glycerin",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["moisturizing", "body wash", "paraben-free"],
    image: "/products/DOVE-Nourishing.jpg",
    link: "https://amzn.to/41ZEWix",
  },
  {
    id: 8,
    name: "TRESemmé Keratin Smooth+ Shampoo 1000ml",
    brand: "TRESemmé",
    category: "Hair Care",
    subcat: "Hair Wash",
    mrp: 1370,
    price: 634,
    rating: 4.3,
    reviews: "60k",
    asin: "B07L3ZCJ53",
    badge: "Best for Price",
    description: "72H Frizz Control with Keratin Protein & Argan Oil | Paraben Free Smoothening Shampoo for Dry & Frizzy Hair.",
    specs: {
      "Skin Type": "All, Frizzy, Dull, Normal, Oily, Dry",
      "Key Ingredient": "Keratin Protein, Argan Oil",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["anti-hair loss", "paraben free", "hair wash", "keratin"],
    image: "/products/TRESemmé-Keratin.jpg",
    link: "https://amzn.to/3Q6pAWQ",
  },
  {
    id: 9,
    name: "Deconstruct Gel Sunscreen for Oily skin SPF 50 PA++++ 50gm",
    brand: "Deconstruct",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 349,
    price: 281,
    rating: 4.2,
    reviews: "12.3k",
    asin: "B0B45RB1RV",
    badge: "Top Rated",
    description: "100% Photostable Sunscreen | 4 New Gen UV Filters | In-Vivo | Lightweight, Airy, Non-greasy | For oily, combination, normal skin | For Men & Women.",
    specs: {
      "Skin Type": "Oily, Normal, Combination",
      "Key Ingredient": "UV Filters",
      "Texture": "Gel",
      "Use": "Daily"
    },
    tags: ["sunscreen", "SPF 50", "oily skin", "no white cast"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Deconstruct-Gel.jpg",
    link: "https://amzn.to/47W1AvI",
  },
  {
    id: 10,
    name: "Minimalist 10% Niacinamide Serum with Zinc 60ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Serum",
    mrp: 999,
    price: 950,
    rating: 4.2,
    reviews: "24k",
    asin: "B0DH88LZ11",
    badge: "Skin Reset",
    description: "Reduces Acne Marks, Controls Oil & Minimizes Pores | Vitamin B3 for Blemish-Free, Clear Skin | For Oily & Acne-Prone Skin.",
    specs: {
      "Skin Type": "Oily, Acne-Prone",
      "Key Ingredient": "Niacinamide, Zinc, Vitamin B3",
      "Texture": "Serum",
      "Use": "Daily"
    },
    tags: ["niacinamide", "serum", "acne marks", "pores"],
    concerns: ["acne", "oily skin", "pigmentation"],
    image: "/products/Niacinamide-Serum.jpg",
    link: "https://amzn.to/4ceFxl5",
  },
  {
    id: 11,
    name: "The Ordinary Niacinamide 10% + Zinc 1% 30ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Serum",
    mrp: 600,
    price: 599,
    rating: 4.3,
    reviews: "54k",
    asin: "B01MDTVZTZ",
    badge: "Top Rated",
    description: "Brightening & Smoothing Serum for Blemish-Prone Skin.",
    specs: {
      "Skin Type": "All, Normal, Oily, Dry",
      "Key Ingredient": "Niacinamide, Zinc",
      "Texture": "Serum",
      "Use": "Daily"
    },
    tags: ["niacinamide", "serum", "acne marks", "brightening"],
    concerns: ["acne", "oily skin", "pigmentation"],
    image: "/products/Ordinary-Niacinamide.jpg",
    link: "https://amzn.to/4tFRRBV",
  },
  {
    id: 12,
    name: "Lakme SPF 50 PA++++ Sunscreen Lotion for Bright Skin 100 ml",
    brand: "Lakme",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 669,
    price: 282,
    rating: 4.2,
    reviews: "16.4k",
    asin: "B00CS1KT96",
    badge: "Budget Pick",
    description: "In Vivo Tested | UVA UVB Blue Light Protection | Waterlight | No White Cast | Niacinamide | For All Skin Types | Blocks UV Rays, Reduce Pigmentation.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Niacinamide",
      "Texture": "Lotion",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA++++", "sunscreen", "niacinamide", "budget"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Lakme-SPF50.jpg",
    link: "https://amzn.to/3OCKQD8",
  },
  {
    id: 13,
    name: "WishCare Niacinamide Oil Balance Fluid Sunscreen SPF 50 PA++++ 50ml",
    brand: "WishCare",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 444,
    price: 316,
    rating: 4.5,
    reviews: "5.2k",
    asin: "B0CW1N7QRT",
    badge: "Value Deal",
    description: "In-Vivo Tested | 8Hrs+ SPF Protection | Lightweight, Matte & No White Cast | Sunscreen SPF 50 For Oily Skin, Sensitive, Dry & Combination Skin | For Women & Men.",
    specs: {
      "Skin Type": "Oily, Sensitive, Dry, Combination",
      "Key Ingredient": "Niacinamide, Zinc PCA, CICA, Ceramides",
      "Texture": "Lotion",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA++++", "sunscreen", "niacinamide", "matte"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/WishCare-Niacinamide.jpg",
    link: "https://amzn.to/3Qgw99h",
  },
  {
    id: 14,
    name: "Dot & Key Watermelon Hyaluronic Serum",
    brand: "Dot & Key",
    category: "Skincare",
    subcat: "Serum",
    mrp: 449,
    price: 400,
    rating: 4.2,
    reviews: "849",
    asin: "B0FG2PQVK5",
    badge: "Hydration Pick",
    description: "Triple Hyaluronic Acid + Watermelon Extract for deep, lasting hydration. Lightweight, non-sticky formula that absorbs instantly. Perfect for dehydrated skin or anyone sitting in AC all day.",
    specs: {
      "Skin Type": "Dry, Dehydrated, Normal",
      "Key Ingredient": "Hyaluronic Acid, Watermelon Extract, Niacinamide",
      "Texture": "Gel-Serum",
      "Use": "AM & PM"
    },
    tags: ["hydration", "hyaluronic acid", "serum", "dry skin", "watermelon"],
    image: "/products/DotAndKey-Watermelon-Serum.jpg",
    link: "https://amzn.to/3OcSTGJ",
  },
  {
    id: 15,
    name: "Plum 15% Vitamin C Face Serum",
    brand: "Plum",
    category: "Skincare",
    subcat: "Serum",
    mrp: 550,
    price: 445,
    rating: 4.0,
    reviews: "14.6k",
    asin: "B095PRGHDX",
    badge: "Glow Booster",
    description: "Stable 15% Vitamin C with mandarin peel extract targets dullness, pigmentation, and uneven tone. Vegan and cruelty-free. Use in the morning before SPF for best results.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Vitamin C, Mandarin Peel Extract",
      "Concentration": "15% Vitamin C",
      "Use": "AM preferred"
    },
    tags: ["vitamin c", "brightening", "serum", "glow", "pigmentation"],
    concerns: ["pigmentation", "glow"],
    image: "/products/Plum-15.jpg",
    link: "https://amzn.to/4t7YmO1",
  },
  {
    id: 16,
    name: "Minimalist Retinol 0.3% + Squalane Serum",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Serum",
    mrp: 599,
    price: 569,
    rating: 4.2,
    reviews: "8.3k",
    asin: "B091JG3GJ5",
    badge: "Anti-Ageing",
    description: "Entry-level retinol (0.3%) in squalane base for a gentler introduction to vitamin A. Reduces fine lines, improves skin texture, and speeds up cell turnover. Night use only — always follow with SPF the next morning.",
    specs: {
      "Skin Type": "Normal, Combination, Oily",
      "Key Ingredient": "Retinol, Squalane",
      "Concentration": "0.3% Retinol",
      "Use": "PM only"
    },
    tags: ["retinol", "anti-ageing", "fine lines", "night serum", "squalane"],
    concerns: ["anti-ageing"],
    image: "/products/Minimalist-Retinol.jpg",
    link: "https://amzn.to/3OExEO6",
  },
  {
    id: 17,
    name: "Neutrogena Hydro Boost Water Gel Moisturiser",
    brand: "Neutrogena",
    category: "Skincare",
    subcat: "Moisturiser",
    mrp: 1050,
    price: 730,
    rating: 4.4,
    reviews: "10.4k",
    asin: "B00BQFTQW6",
    badge: "Dermat Approved",
    description: "Cult-favourite oil-free gel moisturiser with hyaluronic acid. Absorbs in seconds, keeps skin hydrated for 48 hours. The go-to for oily skin types who think they don't need a moisturiser — you do, just this one.",
    specs: {
      "Skin Type": "Oily, Combination",
      "Key Ingredient": "Hyaluronic Acid",
      "Texture": "Water Gel",
      "Use": "AM & PM"
    },
    tags: ["moisturiser", "hyaluronic acid", "gel", "oily skin", "oil-free"],
    concerns: ["dry skin"],
    image: "/products/Neutrogena-Hydro.jpg",
    link: "https://amzn.to/3Qa5pau",
  },
  {
    id: 18,
    name: "Cetaphil Moisturising Cream 250g",
    brand: "Cetaphil",
    category: "Skincare",
    subcat: "Moisturiser",
    mrp: 1349,
    price: 1317,
    rating: 4.5,
    reviews: "4.2k",
    asin: "B099MJH88B",
    badge: "Sensitive Skin",
    description: "The dermatologist gold standard for sensitive and dry skin. Fragrance-free, non-comedogenic, gentle enough for eczema-prone skin. Works on both face and body — one product, fewer decisions.",
    specs: {
      "Skin Type": "Sensitive, Dry",
      "Key Ingredient": "Glycerin, Niacinamide",
      "Weight": "250g",
      "Use": "AM & PM"
    },
    tags: ["moisturiser", "sensitive skin", "dry skin", "fragrance-free", "eczema"],
    concerns: ["dry skin"],
    image: "/products/Cetaphil-Moisturisingz.jpg",
    link: "https://amzn.to/3NYBSQA",
  },
  {
    id: 19,
    name: "Maybelline Fit Me Matte+Poreless Foundation",
    brand: "Maybelline",
    category: "Makeup",
    subcat: "Foundation",
    mrp: 629,
    price: 324,
    rating: 4.2,
    reviews: "21.2k",
    asin: "B087XFYCDQ",
    badge: "Bestseller",
    description: "India's most-used drugstore foundation. Matte finish that blurs pores and holds through 8-hour work days in Indian humidity. Medium-to-full buildable coverage without looking cakey.",
    specs: {
      "Skin Type": "Oily, Combination",
      "Finish": "Matte",
      "Coverage": "Medium to Full",
      "Use": "Daily"
    },
    tags: ["foundation", "matte", "oily skin", "coverage", "makeup"],
    image: "/products/Maybelline-New.jpg",
    link: "https://amzn.to/4tCP38S",
  },
  {
    id: 20,
    name: "L'Oréal Paris Kajal Magique",
    brand: "L'Oréal Paris",
    category: "Makeup",
    subcat: "Kajal",
    mrp: 449,
    price: 269,
    rating: 4.1,
    reviews: "6.2k",
    asin: "B01BY5KDEC",
    badge: "Top Rated",
    description: "Intensely pigmented kajal that actually stays put in Indian heat and humidity. Smooth glide, waterproof formula, and 12-hour wear. One of the most consistently reviewed eye products in India for a reason.",
    specs: {
      "Type": "Kajal",
      "Finish": "Matte",
      "Waterproof": "Yes",
      "Longevity": "12 hours"
    },
    tags: ["kajal", "eyeliner", "smudge-proof", "waterproof", "eyes"],
    image: "/products/L'Oréal-Paris.jpg",
    link: "https://amzn.to/4c9CAUn",
  },
  {
    id: 21,
    name: "WOW Skin Science Apple Cider Vinegar Shampoo",
    brand: "WOW Skin Science",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 374,
    price: 319,
    rating: 3.8,
    reviews: "45k",
    asin: "B09M8NN8DQ",
    badge: "Trending",
    description: "ACV shampoo that balances scalp pH, reduces dandruff, and clears product buildup. Sulphate-free and silicone-free. Especially effective during monsoon when oily scalp gets out of hand.",
    specs: {
      "Key Ingredient": "Apple Cider Vinegar",
      "Sulphate-Free": "Yes",
      "Silicone-Free": "Yes",
      "Best For": "Oily scalp, dandruff, buildup"
    },
    tags: ["shampoo", "apple cider vinegar", "scalp", "dandruff", "sulphate-free"],
    image: "/products/Wow-Skin.jpg",
    link: "https://amzn.to/4tCPAaS",
  },
  {
    id: 22,
    name: "Indulekha Bringha Hair Oil",
    brand: "Indulekha",
    category: "Hair Care",
    subcat: "Hair Oil",
    mrp: 999,
    price: 572,
    rating: 4.1,
    reviews: "74k",
    asin: "B086QDT64L",
    badge: "Ayurvedic Pick",
    description: "The ayurvedic hair oil with actual clinical backing. Bringharaj (eclipta alba) is one of the few traditional ingredients with published studies on hair growth. Loved by Indian grandmothers and dermatologists alike.",
    specs: {
      "Key Ingredient": "Bringharaj (Eclipta Alba)",
      "Type": "Hair Oil",
      "Best For": "Hair fall, scalp health, growth",
      "Ayurvedic": "Yes"
    },
    tags: ["hair oil", "bringha", "ayurvedic", "hair fall", "growth"],
    image: "/products/Indulekha-Bringha.jpg",
    link: "https://amzn.to/4t4zLd7",
  },
  {
    id: 23,
    name: "Dot & Key Vitamin C + E Super Bright Body Lotion",
    brand: "Dot & Key",
    category: "Body Care",
    subcat: "Body Lotion",
    mrp: 359,
    price: 316,
    rating: 4.2,
    reviews: "1.4k",
    asin: "B0CHJTCGS3",
    badge: "Glow Pick",
    description: "Lightweight body lotion with Vitamin C, E and Niacinamide that targets tan lines, uneven body tone, and dullness. All the concerns Indian skin deals with — especially on arms, legs, and neck.",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Vitamin C, Vitamin E, Niacinamide",
      "Best For": "Tan removal, brightening, uneven tone",
      "Fragrance": "Light"
    },
    tags: ["body lotion", "vitamin c", "brightening", "tan removal", "niacinamide"],
    image: "/products/Dot-Key-Vitamin.jpg",
    link: "https://amzn.to/4t7Wq8d",
  },
  {
    id: 24,
    name: "Vaseline Cocoa Radiant Body Lotion",
    brand: "Vaseline",
    category: "Body Care",
    subcat: "Body Lotion",
    mrp: 799,
    price: 720,
    rating: 4.2,
    reviews: "4.7k",
    asin: "B0059MUJR8",
    badge: "Best for Price",
    description: "No-nonsense daily body moisturiser with cocoa butter. Absorbs without greasiness, keeps dry skin comfortable through the day. One of the best-value body lotions in India.",
    specs: {
      "Skin Type": "Dry, Normal",
      "Key Ingredient": "Cocoa Butter, Petroleum Jelly",
      "Fragrance": "Light cocoa",
      "Use": "Daily"
    },
    tags: ["body lotion", "cocoa", "dry skin", "affordable", "moisturiser"],
    image: "/products/Vaseline-cream.jpg",
    link: "https://amzn.to/420LNs2",
  },
  {
    id: 25,
    name: "Himalaya Wellness Ashwagandha Tablets — 60 Tab",
    brand: "Himalaya",
    category: "Wellness",
    subcat: "Supplement",
    mrp: 228,
    price: 228,
    rating: 4.2,
    reviews: "40.3k",
    asin: "B01DQV8BIM",
    badge: "Adaptogen",
    description: "One of the most studied adaptogens for stress, cortisol regulation, and sleep quality. Relevant to skin too — chronic stress is a major driver of breakouts and dullness. Himalaya's standardised formulation is among the most trusted in India.",
    specs: {
      "Count": "60 Tablets",
      "Key Ingredient": "Ashwagandha Root Extract",
      "Dose": "1-2 tablets daily",
      "Vegetarian": "Yes"
    },
    tags: ["ashwagandha", "adaptogen", "wellness", "stress", "supplement", "ayurvedic"],
    image: "/products/Himalaya-Ashwagandha.jpg",
    link: "https://amzn.to/4td8ZPU",
  },
  {
    id: 26,
    name: "Himalaya Purifying Neem Face Wash 150ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 279,
    price: 205,
    rating: 4.4,
    reviews: "12.6k",
    asin: "B010Z0LH8I",
    badge: "Budget Pick",
    description: "Soap-free herbal neem and turmeric face wash that clears pimples and prevents acne. Natural antibacterial properties for oily and acne-prone skin.",
    specs: {
      "Skin Type": "All, Oily, Acne-Prone",
      "Key Ingredient": "Neem, Turmeric",
      "Texture": "Gel",
      "Use": "Daily"
    },
    tags: ["neem", "acne", "face wash", "himalaya"],
    image: "/products/Himalaya-Purifying.jpg",
    link: "https://amzn.to/4sOGsz7"
  },
  {
    id: 27,
    name: "Himalaya Neem Face Wash 100ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 199,
    price: 139,
    rating: 4.3,
    reviews: "7.8k",
    asin: "B002Q5JE2C",
    badge: "Value Deal",
    description: "Compact 100ml neem face wash with turmeric. Perfect for travel and daily use. Antibacterial and anti-inflammatory formula.",
    specs: {
      "Skin Type": "All, Oily, Combination",
      "Key Ingredient": "Neem, Turmeric",
      "Texture": "Gel",
      "Use": "Twice Daily"
    },
    tags: ["neem", "turmeric", "travel-size", "face wash"],
    image: "/products/Himalaya-Purifying-Neem.jpg",
    link: "https://amzn.to/3OOV6Z8"
  },
  {
    id: 28,
    name: "Himalaya Neem Face Wash 400ml Pack of 2",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 599,
    price: 599,
    rating: 4.3,
    reviews: "7k+",
    asin: "B0B5X5S8GY",
    badge: "Best Value",
    description: "Large 400ml bottle of Himalaya neem face wash with proven acne-fighting formula. Lasts months with daily use. Best for oily skin.",
    specs: {
      "Skin Type": "All, Oily, Acne-Prone",
      "Key Ingredient": "Neem, Turmeric",
      "Texture": "Gel",
      "Size": "400ml"
    },
    tags: ["neem", "large-size", "value", "acne"],
    image: "/products/Purifying-Neem-Face.jpg",
    link: "https://amzn.to/4ezkwV4"
  },

  {
    id: 29,
    name: "Himalaya Purifying Neem Foaming Face Wash, 150Ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 299,
    price: 190,
    rating: 4.3,
    reviews: "7k",
    asin: "B003OPE57C",
    badge: "Foaming Formula",
    description: "Foaming face wash with turmeric and neem. Creates a luxurious lather while gently cleansing. Soap-free formula suitable for all skin types.",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Turmeric, Neem",
      "Texture": "Foaming Gel",
      "Use": "Daily"
    },
    tags: ["foaming", "turmeric", "neem", "lather"],
    image: "/products/Himalaya-Purifying-Neem-Foaming.jpg",
    link: "https://amzn.to/4eFqaoy"
  },

   {
    id: 30,
    name: "Himalaya Brightening Vitamin C Orange Face Wash 100ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 209,
    price: 138,
    rating: 4.2,
    reviews: "700",
    asin: "B0CNTFMSWV",
    badge: "Brightening",
    description: "Vitamin C enriched face wash with orange extract. Brightens dull skin and removes tanning. Gentle enough for daily use.",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Vitamin C, Orange Extract",
      "Texture": "Gel",
      "Use": "Daily"
    },
    tags: ["vitamin-c", "brightening", "orange", "tan-removal"],
    image: "/products/Himalaya-Brightening-Vitamin-C.jpg",
    link: "https://amzn.to/3OCB9ES"
  },

  {
    id: 31,
    name: "The Ordinary Glycolic Acid 7% Exfoliating Toner 240ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Hydrating Essence",
    mrp: 1275,
    price: 1275,
    rating: 4.4,
    reviews: "37k",
    asin: "B071914GGL",
    badge: "Hydrating",
    description: "Pure glycerin with minimal water. Highly humectant ingredient that draws moisture into skin. Can be used alone or mixed with other products.",
    specs: {
      "Skin Type": "All, Dry, Dehydrated",
      "Key Ingredient": "Glycerin 99%",
      "Texture": "Liquid",
      "Use": "Daily"
    },
    tags: ["glycerin", "hydration", "humectant", "moisturizing"],
    image: "/products/Ordinary-Glycolic -Acid-7.jpg",
    link: "https://amzn.to/41MA9Rt"
  },

  {
    id: 32,
    name: "The Ordinary Salicylic Acid 2% Solution 30ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Exfoliating Essence",
    mrp: 600,
    price: 599,
    rating: 4.1,
    reviews: "8.2k",
    asin: "B0C3PCJ6SD",
    badge: "Exfoliating",
    description: "Liquid exfoliant with 2% salicylic acid. Unclogs pores and reduces acne. Leave-on formula that works overnight for clear skin.",
    specs: {
      "Skin Type": "Oily, Acne-Prone, All",
      "Key Ingredient": "Salicylic Acid 2%",
      "Texture": "Liquid",
      "Use": "PM only"
    },
    tags: ["salicylic-acid", "exfoliant", "acne", "pores"],
    image: "/products/Ordinary-Salicylic- Acid.jpg",
    link: "https://amzn.to/4sQOxDx"
  },
    {
    id: 33,
    name: "The Ordinary Hyaluronic Acid 2% + B5 30ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Hydrating Essence",
    mrp: 1000,
    price: 1000,
    rating: 4.6,
    reviews: "33k",
    asin: "B01MYEZPC8",
    badge: "Hydrating",
    description: "Lightweight hydrating serum with hyaluronic acid and panthenol. Plumps skin and maintains moisture. Works for all skin types.",
    specs: {
      "Skin Type": "All, Dry, Dehydrated",
      "Key Ingredient": "Hyaluronic Acid, B5",
      "Texture": "Liquid",
      "Use": "Daily"
    },
    tags: ["hyaluronic-acid", "panthenol", "hydration", "plumping"],
    image: "/products/Ordinary-Hyaluronic-Acid.jpg",
    link: "https://amzn.to/4mNmNyg"
  },
  {
    id: 34,
    name: "Plum Green Tea Face Toner 200ml",
    brand: "Plum",
    category: "Skincare",
    subcat: "Toner",
    mrp: 390,
    price: 378,
    rating: 4.2,
    reviews: "14k",
    asin: "B00OCJ5M6C",
    badge: "Green Tea",
    description: "Plum Green Tea Face Toner For Oily, Acne-Prone Skin | With Glycolic Acid | Alcohol-Free | Fights Pimples | Tightens Pores | Controls Oil | Gently Exfoliates Dead Skin Cells | Women & Men | 200ml.",
    specs: {
      "Skin Type": "Oily, Combination, Acne-Prone",
      "Key Ingredient": "Green Tea, Glycolic Acid",
      "Texture": "Liquid",
      "Use": "AM & PM"
    },
    tags: ["rice-water", "acne", "vegan", "clarifying"],
    image: "/products/Plum-Green-Tea.jpg",
    link: "https://amzn.to/48fE8d5"
  },
  {
    id: 35,
    name: "Plum 3% Niacinamide & Rice Water Face Toner 150ml",
    brand: "Plum",
    category: "Skincare",
    subcat: "Toner",
    mrp: 440,
    price: 449,
    rating: 4.2,
    reviews: "6.5k",
    asin: "B09PV4379W",
    badge: "Hydrating",
    description: "Alcohol-Free Toner for Oily Acne Prone Dry Combination Skin | Pore Tightening & Glowing Skin |Fades Blemishes, Brightens & Smoothens | Women & Men.",
    specs: {
      "Skin Type": "Dry, Dehydrated, All",
      "Key Ingredient": "Rice water, Niacinamide",
      "Texture": "Liquid",
      "Use": "Daily"
    },
    tags: ["rice-water", "Alcohol-Free", "hydration", "glow"],
    image: "/products/Plum-Niacinamide.jpg",
    link: "https://amzn.to/4u2JmB8"
  },
  {
    id: 36,
    name: "Minimalist Multi-Peptide Night Face Serum 30ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Essence",
    mrp: 699,
    price: 629,
    rating: 4.3,
    reviews: "3.8k",
    asin: "B08MVD6T8V",
    badge: "Anti-Ageing",
    description: "Peptide-rich serum that strengthens skin barrier and reduces wrinkles. Multi-peptide blend for comprehensive anti-aging benefits.",
    specs: {
      "Skin Type": "Mature, All Types",
      "Key Ingredient": "Multi-Peptide 10%",
      "Texture": "Serum",
      "Use": "AM & PM"
    },
    tags: ["peptide", "anti-aging", "barrier-repair", "wrinkles"],
    image: "/products/Minimalist-Multi-Peptide.jpg",
    link: "https://amzn.to/41R6Jlq"
  },
  {
    id: 37,
    name: "Dot & Key Watermelon 10% Glycolic Serum Exfoliating Essence 30ml",
    brand: "Dot & Key",
    category: "Skincare",
    subcat: "Exfoliating Essence",
    mrp: 599,
    price: 509,
    rating: 4.2,
    reviews: "300",
    asin: "B0BLRWFM22",
    badge: "Exfoliating",
    description: "Glycolic Serum for Face Glowing, With KojicI | Targets Pigmentation & Dark Spots | Targets Dullness, Uneven Texture, Sebum & Excess Oil | Serum For Oily & Normal Skin.",
    specs: {
      "Skin Type": "Normal, Oily, Combination",
      "Key Ingredient": "Glycolic Acid 8%",
      "Texture": "Liquid",
      "Use": "2-3x Weekly"
    },
    tags: ["glycolic-acid", "exfoliant", "brightening", "watermelon", "aha"],
    image: "/products/Dot-Key-Watermelon.jpg",
    link: "https://amzn.to/4tuB8BV"
  },
   {
    id: 38,
    name: "Mamaearth Onion Hair Oil 50ml",
    brand: "Mamaearth",
    category: "Hair care",
    subcat: "Oil",
    mrp: 177,
    price: 171,
    rating: 4,
    reviews: "56k",
    asin: "B0CF61RF5B",
    badge: "Natural",
    description: "Onion Hair Oil for Hair Growth & Hair Fall Control with Redensyl .",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Onion Extract",
      "Texture": "Liquid",
      "Use": "Daily"
    },
    tags: ["onion", "brightening", "natural", "organic"],
    image: "/products/Mamaearth-Onion-Hair-Oil.jpg",
    link: "https://amzn.to/4cK4buo"
  },
  {
  id: 39,
  name: "Maybelline New York Fit Me Glow",
  brand: "Maybelline",
  category: "Makeup",
  subcat: "BB Cream",
  mrp: 429,
  price: 343,
  rating: 4.7,
  reviews: "133",
  asin: "B0GJ5N15GG",
  badge: "Niacinamide",
  description: "INSTANT + OVERTIME GLOW BB Cream: Unlock luminous, dewy glow, natural coverage, and all-day hydration with Maybelline Fit Me Nude Glow BB cream. Blends seamlessly without heaviness for a fresh, natural look.",
  specs: {
    "Skin Type": "All",
    "Key Ingredient": "Niacinamide, Hyaluronic Acid",
    "Texture": "Cream",
    "Use": "On face"
  },
  tags: ["niacinamide", "bb-cream", "hydrating", "glow"],
  image: "/products/Maybelline-Fit.jpg",
  link: "https://amzn.to/4mVn2r6r"
},

{
  id: 40,
  name: "L'Oréal True Match Foundation",
  brand: "L'Oréal",
  category: "Makeup",
  subcat: "Foundation",
  mrp: 2887,
  price: 1817,
  rating: 4.5,
  reviews: "620",
  asin: "B00112HQIU",
  badge: "SPF 17",
  description: "L'Oreal Paris True Match Super-Blendable Foundation, Natural Ivory, 1 fl. oz. Natural finish with lightweight coverage.",
  specs: {
    "Skin Type": "All",
    "Key Ingredient": "Titanium Dioxide, Glycerin",
    "Texture": "Liquid",
    "Use": "On face"
  },
  tags: ["glycerin", "foundation", "natural-finish", "spf"],
  image: "/products/True-Match.jpg",
  link: "https://amzn.to/4u9B8Y0"
}

];