export const PRODUCTS = [
  {
    id: 103,
    name: "The Ordinary Caffeine Solution 5% + EGCG, Depuffing Eye Serum for Dark Circles and Tired Eyes, 30",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Eye Serum",
    mrp: 900,
    price: 900,
    rating: 4.1,
    reviews: "32k",
    asin: "B01MUZVE1C",
    badge: "For Puffiness",
    description: "Highly concentrated 5% caffeine and EGCG from green tea leaves. Clinically proven to reduce the look of puffiness and vascular dark circles.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Caffeine, EGCG",
      "Texture": "Serum",
      "Use": "AM & PM"
    },
    tags: ["caffeine", "eye serum", "dark circles", "puffiness", "the ordinary"],
    concerns: ["dark circles", "pigmentation"],
    image: "/products/ordinary-caffeine.jpg",
    link: "https://amzn.to/4n69skw",
    cultBeautyLink: "https://www.cultbeauty.com/the-ordinary-caffeine-solution-5-egcg-30ml/11494541.html"
  },
  {
    id: 104,
    name: "Minimalist Vitamin K + Retinal 01% Under Eye Cream 14 gm",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Eye Cream",
    mrp: 599,
    price: 474,
    rating: 4.2,
    reviews: "4.5k",
    asin: "MINIMALISTK",
    badge: "For Pigmentation",
    description: "Reduces Dark Circles, Wrinkles & Fine Lines. Formulated with Vitamin K and Retinal 0.1% to target structural pigmentation and aging, plus Caffeine for puffiness.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Vitamin K, Retinal 0.1%, Caffeine",
      "Texture": "Cream",
      "Use": "PM"
    },
    tags: ["eye cream", "dark circles", "minimalist", "vitamin k", "retinal", "anti-aging"],
    concerns: ["dark circles", "anti-ageing", "pigmentation"],
    image: "/products/minimalist-eye.jpg",
    link: "https://amzn.to/42eKwxO"
  },
  {
    id: 101,
    name: "Mighty Patch Hero Cosmetics Patches Hydrocolloid (36 Patches)",
    brand: "Hero Cosmetics",
    category: "Skincare",
    subcat: "Spot Treatment",
    mrp: 999,
    price: 759,
    rating: 4.6,
    reviews: "125k",
    asin: "MIGHTYPATCH",
    badge: "Overnight Fix",
    description: "Award-winning hydrocolloid patches that extract impurities and protect blemishes from bacteria. Visibly flattens pimples overnight.",
    specs: {
      "Skin Type": "Acne-Prone, All",
      "Key Ingredient": "Hydrocolloid",
      "Type": "Patch",
      "Use": "Overnight"
    },
    tags: ["pimple patch", "acne", "spot treatment", "mighty patch", "hero cosmetics", "hydrocolloid"],
    concerns: ["acne"],
    image: "/products/mighty-patch.jpg",
    link: "https://amzn.to/4cQOt1O",
    cultBeautyLink: "https://www.cultbeauty.com/hero-cosmetics-mighty-patch-original-36-patches/14299948.html"
  },
  {
    id: 102,
    name: "BENZAC AC 2.5% - Tube of 30 g Gel",
    brand: "Galderma",
    category: "Skincare",
    subcat: "Spot Treatment",
    mrp: 230,
    price: 195,
    rating: 4.2,
    reviews: "8.5k",
    asin: "BENZAC25",
    badge: "Dermat Pick",
    description: "2.5% Benzoyl Peroxide (BPO) gel. Kills acne-causing bacteria on contact and reduces inflammation. The most clinically proven OTC acne treatment.",
    specs: {
      "Skin Type": "Acne-Prone",
      "Key Ingredient": "Benzoyl Peroxide 2.5%",
      "Texture": "Gel",
      "Use": "Spot treatment only"
    },
    tags: ["benzoyl peroxide", "bpo", "acne", "spot treatment", "bacteria", "benzac"],
    concerns: ["acne"],
    image: "/products/benzac-ac.jpg",
    link: "https://amzn.to/4d6uc76"
  },
  {
    id: 1,
    name: "Cetaphil Gentle Skin Hydrating Face Wash 118ml",
    brand: "Cetaphil",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 459,
    price: 384,
    rating: 4.5,
    reviews: "1.3L+",
    asin: "B01CCGW4OE",
    badge: "Top Rated",
    description: "Paraben Free, Sulphate-Free Gentle Skin Hydrating Cleanser with Niacinamide, Vitamin B5 for Dry to Normal, Sensitive Skin.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Glycerin",
      "Texture": "Gel",
      "Use": "Daily cleanser"
    },
    tags: ["cleanser", "gentle", "face wash", "cetaphil"],
    image: "/products/cetaphil-facewash.jpg",
    cultBeautyLink: "https://www.cultbeauty.com/cetaphil-gentle-skin-cleanser-236ml/13735073.html"
  },
  {
    id: 2,
    name: "Simple Kind To Skin Moisturising Facial Wash, 150 ml",
    brand: "Unilever",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 420,
    price: 329,
    rating: 4.2,
    reviews: "5.5k",
    asin: "B00V4R0ET0",
    badge: "Bestseller",
    description: "100% Soap-Free Moisturising Facewash with Panthenol for dry, sensitive skin | Reduces Visual Dryness & Strengthens Skin Barrier.",
    specs: {
      "Skin Type": "Dry, Sensitive",
      "Key Ingredient": "Glycerin",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["Vitamin-E", "Panthenol", "Pro Amino"],
    image: "/products/Simple-Moisturising.jpg",
    link: "https://amzn.to/48nWKaG",
  },
  {
    id: 3,
    name: "Minimalist 7% ALA + Glycolic Brightening Face Wash 100ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 399,
    price: 380,
    rating: 4.2,
    reviews: "3.2k",
    asin: "B09VLDY46B",
    badge: "Trending Now",
    description: "Gentle Exfoliating Cleanser for Glowing Skin & Oil Control, Sulphate Free.",
    specs: {
      "Skin Type": "All, Combination, Dry, Normal, Oily, Sensitive",
      "Key Ingredient": "Glycolic Acid",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["Alpha Lipoic Acid", "Vitamin B5", "face wash"],
    image: "/products/Minimalist-ALA.jpg",
    link: "https://amzn.to/4cn8R9n",
  },
  {
    id: 4,
    name: "Minimalist Sunscreen SPF 50 PA+++ with Niacinamide & Multi-Vitamins 100gm",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 699,
    price: 533,
    rating: 4.1,
    reviews: "31.3k",
    asin: "B0DHY6LQTW",
    badge: "Smart Buy",
    description: "Clinically Tested in US (In-Vivo) | Lightweight with Multi-Vitamins | No White Cast | Broad Spectrum | Face Sunscreen for Men & Women | 100gm.",
    specs: {
      "Skin Type": "All, Combination, Dry, Normal, Oily, Sensitive",
      "Key Ingredient": "Niacinamide, Multi-Vitamins",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA+++", "Niacinamide", "Multi-Vitamins"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Minimalist-Sunscreen.jpg",
    link: "https://amzn.to/4muroFm",
  },
  {
    id: 5,
    name: "Aqualogica Radiance+ Dewy Sunscreen with Watermelon & Niacinamide with SPF 50 & PA++++ - 80g",
    brand: "Aqualogica",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 599,
    price: 388,
    rating: 4.1,
    reviews: "10k",
    asin: "B0C9JPWLR4",
    badge: "Best for Price",
    description: "Broad Spectrum SPF 50+ PA++++ | UVA/B & Blue Light Protection | Anti-Pollution Factor (APF) Technology | In Vivo Tested | Ideal for Oily Skin Type | Fragrance-Free & No White Cast | For Radiant Skin.",
    specs: {
      "Skin Type": "All, Combination, Dry, Normal, Oily, Sensitive",
      "Key Ingredient": "Hyaluronic Acid, Niacinamide, Watermelon",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA++++", "Niacinamide", "Anti-Pollution"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Aqualogica-Radiance.jpg",
    link: "https://amzn.to/3OcJtLm",
  },
  {
    id: 6,
    name: "mCaffeine Exfoliating Coffee Body Scrub Powder Jar 100gm",
    brand: "mCaffeine",
    category: "Body Care",
    subcat: "Body Scrub",
    mrp: 449,
    price: 369,
    rating: 4.3,
    reviews: "27.4k",
    asin: "B07K4BFQK1",
    badge: "Bestseller",
    description: "mCaffeine Exfoliating Coffee Body Scrub Powder Jar for Tan Removal & Soft-Smooth Skin | De-Tan Bathing Scrub With Coconut Oil | Removes Dirt & Dead Skin | All Skin Types.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Coffee, Caffeine, Coconut Oil",
      "Texture": "Powder",
      "Use": "Daily"
    },
    tags: ["exfoliating", "body scrub", "tan removal", "coffee"],
    image: "/products/mCaffeine-Exfoliating.jpg",
    link: "https://amzn.to/4eerGxJ",
  },
  {
    id: 7,
    name: "DOVE Nourishing Bodywash, 825ml",
    brand: "Dove",
    category: "Body Care",
    subcat: "Body Wash",
    mrp: 560,
    price: 302,
    rating: 4.4,
    reviews: "29k",
    asin: "B07S7R626P",
    badge: "Best for Price",
    description: "For Soft and Smooth Skin, with Triple Hydration Serum & Glycerine, Dermatologically Tested, Paraben-Free, Sulphate-Free.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Glycerin",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["moisturizing", "body wash", "paraben-free"],
    image: "/products/DOVE-Nourishing.jpg",
    link: "https://amzn.to/41ZEWix",
  },
  {
    id: 8,
    name: "TRESemmé Keratin Smooth+ Shampoo 1000ml",
    brand: "TRESemmé",
    category: "Hair Care",
    subcat: "Hair Wash",
    mrp: 1370,
    price: 634,
    rating: 4.3,
    reviews: "60k",
    asin: "B07L3ZCJ53",
    badge: "Best for Price",
    description: "72H Frizz Control with Keratin Protein & Argan Oil | Paraben Free Smoothening Shampoo for Dry & Frizzy Hair.",
    specs: {
      "Skin Type": "All, Frizzy, Dull, Normal, Oily, Dry",
      "Key Ingredient": "Keratin Protein, Argan Oil",
      "Texture": "Cream",
      "Use": "Daily"
    },
    tags: ["anti-hair loss", "paraben free", "hair wash", "keratin"],
    image: "/products/TRESemmé-Keratin.jpg",
    link: "https://amzn.to/3Q6pAWQ",
  },
  {
    id: 9,
    name: "Deconstruct Gel Sunscreen for Oily skin SPF 50 PA++++ 50gm",
    brand: "Deconstruct",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 349,
    price: 281,
    rating: 4.2,
    reviews: "12.3k",
    asin: "B0B45RB1RV",
    badge: "Top Rated",
    description: "100% Photostable Sunscreen | 4 New Gen UV Filters | In-Vivo | Lightweight, Airy, Non-greasy | For oily, combination, normal skin | For Men & Women.",
    specs: {
      "Skin Type": "Oily, Normal, Combination",
      "Key Ingredient": "UV Filters",
      "Texture": "Gel",
      "Use": "Daily"
    },
    tags: ["sunscreen", "SPF 50", "oily skin", "no white cast"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Deconstruct-Gel.jpg",
    link: "https://amzn.to/47W1AvI",
  },
  {
    id: 10,
    name: "Minimalist 10% Niacinamide Serum with Zinc 60ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Serum",
    mrp: 999,
    price: 950,
    rating: 4.2,
    reviews: "24k",
    asin: "B0DH88LZ11",
    badge: "Skin Reset",
    description: "Reduces Acne Marks, Controls Oil & Minimizes Pores | Vitamin B3 for Blemish-Free, Clear Skin | For Oily & Acne-Prone Skin.",
    specs: {
      "Skin Type": "Oily, Acne-Prone",
      "Key Ingredient": "Niacinamide, Zinc, Vitamin B3",
      "Texture": "Serum",
      "Use": "Daily"
    },
    tags: ["niacinamide", "serum", "acne marks", "pores"],
    concerns: ["acne", "oily skin", "pigmentation"],
    image: "/products/Niacinamide-Serum.jpg",
    link: "https://amzn.to/4ceFxl5",
  },
  {
    id: 11,
    name: "The Ordinary Niacinamide 10% + Zinc 1% 30ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Serum",
    mrp: 600,
    price: 599,
    rating: 4.3,
    reviews: "54k",
    asin: "B01MDTVZTZ",
    badge: "Top Rated",
    description: "Brightening & Smoothing Serum for Blemish-Prone Skin.",
    specs: {
      "Skin Type": "All, Normal, Oily, Dry",
      "Key Ingredient": "Niacinamide, Zinc",
      "Texture": "Serum",
      "Use": "Daily"
    },
    tags: ["niacinamide", "serum", "acne marks", "brightening"],
    concerns: ["acne", "oily skin", "pigmentation"],
    image: "/products/Ordinary-Niacinamide.jpg",
    link: "https://amzn.to/4tFRRBV",
    cultBeautyLink: "https://www.cultbeauty.com/the-ordinary-niacinamide-10-zinc-1-30ml/11364731.html"
  },
  {
    id: 12,
    name: "Lakme SPF 50 PA++++ Sunscreen Lotion for Bright Skin 100 ml",
    brand: "Lakme",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 669,
    price: 282,
    rating: 4.2,
    reviews: "16.4k",
    asin: "B00CS1KT96",
    badge: "Budget Pick",
    description: "In Vivo Tested | UVA UVB Blue Light Protection | Waterlight | No White Cast | Niacinamide | For All Skin Types | Blocks UV Rays, Reduce Pigmentation.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Niacinamide",
      "Texture": "Lotion",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA++++", "sunscreen", "niacinamide", "budget"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/Lakme-SPF50.jpg",
    link: "https://amzn.to/3OCKQD8",
  },
  {
    id: 13,
    name: "WishCare Niacinamide Oil Balance Fluid Sunscreen SPF 50 PA++++ 50ml",
    brand: "WishCare",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 444,
    price: 316,
    rating: 4.5,
    reviews: "5.2k",
    asin: "B0CW1N7QRT",
    badge: "Value Deal",
    description: "In-Vivo Tested | 8Hrs+ SPF Protection | Lightweight, Matte & No White Cast | Sunscreen SPF 50 For Oily Skin, Sensitive, Dry & Combination Skin | For Women & Men.",
    specs: {
      "Skin Type": "Oily, Sensitive, Dry, Combination",
      "Key Ingredient": "Niacinamide, Zinc PCA, CICA, Ceramides",
      "Texture": "Lotion",
      "Use": "Daily"
    },
    tags: ["SPF 50 PA++++", "sunscreen", "niacinamide", "matte"],
    concerns: ["sunscreen", "oily skin"],
    image: "/products/WishCare-Niacinamide.jpg",
    link: "https://amzn.to/3Qgw99h",
  },
  {
    id: 14,
    name: "Dot & Key Watermelon Hyaluronic Serum",
    brand: "Dot & Key",
    category: "Skincare",
    subcat: "Serum",
    mrp: 449,
    price: 400,
    rating: 4.2,
    reviews: "849",
    asin: "B0FG2PQVK5",
    badge: "Hydration Pick",
    description: "Triple Hyaluronic Acid + Watermelon Extract for deep, lasting hydration. Lightweight, non-sticky formula that absorbs instantly. Perfect for dehydrated skin or anyone sitting in AC all day.",
    specs: {
      "Skin Type": "Dry, Dehydrated, Normal",
      "Key Ingredient": "Hyaluronic Acid, Watermelon Extract, Niacinamide",
      "Texture": "Gel-Serum",
      "Use": "AM & PM"
    },
    tags: ["hydration", "hyaluronic acid", "serum", "dry skin", "watermelon"],
    image: "/products/DotAndKey-Watermelon-Serum.jpg",
    link: "https://amzn.to/3OcSTGJ",
  },
  {
    id: 15,
    name: "Plum 15% Vitamin C Face Serum",
    brand: "Plum",
    category: "Skincare",
    subcat: "Serum",
    mrp: 550,
    price: 445,
    rating: 4.0,
    reviews: "14.6k",
    asin: "B095PRGHDX",
    badge: "Glow Booster",
    description: "Stable 15% Vitamin C with mandarin peel extract targets dullness, pigmentation, and uneven tone. Vegan and cruelty-free. Use in the morning before SPF for best results.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Vitamin C, Mandarin Peel Extract",
      "Concentration": "15% Vitamin C",
      "Use": "AM preferred"
    },
    tags: ["vitamin c", "brightening", "serum", "glow", "pigmentation"],
    concerns: ["pigmentation", "glow"],
    image: "/products/Plum-15.jpg",
    link: "https://amzn.to/4t7YmO1",
  },
  {
    id: 16,
    name: "Minimalist Retinol 0.3% + Squalane Serum",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Serum",
    mrp: 599,
    price: 569,
    rating: 4.2,
    reviews: "8.3k",
    asin: "B091JG3GJ5",
    badge: "Anti-Ageing",
    description: "Entry-level retinol (0.3%) in squalane base for a gentler introduction to vitamin A. Reduces fine lines, improves skin texture, and speeds up cell turnover. Night use only — always follow with SPF the next morning.",
    specs: {
      "Skin Type": "Normal, Combination, Oily",
      "Key Ingredient": "Retinol, Squalane",
      "Concentration": "0.3% Retinol",
      "Use": "PM only"
    },
    tags: ["retinol", "anti-ageing", "fine lines", "night serum", "squalane"],
    concerns: ["anti-ageing"],
    image: "/products/Minimalist-Retinol.jpg",
    link: "https://amzn.to/3OExEO6",
  },
  {
    id: 17,
    name: "Neutrogena Hydro Boost Water Gel Moisturiser",
    brand: "Neutrogena",
    category: "Skincare",
    subcat: "Moisturiser",
    mrp: 1050,
    price: 730,
    rating: 4.4,
    reviews: "10.4k",
    asin: "B00BQFTQW6",
    badge: "Dermat Approved",
    description: "Cult-favourite oil-free gel moisturiser with hyaluronic acid. Absorbs in seconds, keeps skin hydrated for 48 hours. The go-to for oily skin types who think they don't need a moisturiser — you do, just this one.",
    specs: {
      "Skin Type": "Oily, Combination",
      "Key Ingredient": "Hyaluronic Acid",
      "Texture": "Water Gel",
      "Use": "AM & PM"
    },
    tags: ["moisturiser", "hyaluronic acid", "gel", "oily skin", "oil-free"],
    concerns: ["dry skin"],
    image: "/products/Neutrogena-Hydro.jpg",
    link: "https://amzn.to/3Qa5pau",
    cultBeautyLink: "https://www.cultbeauty.com/neutrogena-hydro-boost-water-gel-moisturiser-50ml/13768469.html"
  },
  {
    id: 18,
    name: "Cetaphil Moisturising Cream 250g",
    brand: "Cetaphil",
    category: "Skincare",
    subcat: "Moisturiser",
    mrp: 1349,
    price: 1317,
    rating: 4.5,
    reviews: "4.2k",
    asin: "B099MJH88B",
    badge: "Sensitive Skin",
    description: "The dermatologist gold standard for sensitive and dry skin. Fragrance-free, non-comedogenic, gentle enough for eczema-prone skin. Works on both face and body — one product, fewer decisions.",
    specs: {
      "Skin Type": "Sensitive, Dry",
      "Key Ingredient": "Glycerin, Niacinamide",
      "Weight": "250g",
      "Use": "AM & PM"
    },
    tags: ["moisturiser", "sensitive skin", "dry skin", "fragrance-free", "eczema"],
    concerns: ["dry skin"],
    image: "/products/Cetaphil-Moisturisingz.jpg",
    link: "https://amzn.to/3NYBSQA",
  },
  {
    id: 19,
    name: "Maybelline Fit Me Matte+Poreless Foundation",
    brand: "Maybelline",
    category: "Makeup",
    subcat: "Foundation",
    mrp: 629,
    price: 324,
    rating: 4.2,
    reviews: "21.2k",
    asin: "B087XFYCDQ",
    badge: "Bestseller",
    description: "India's most-used drugstore foundation. Matte finish that blurs pores and holds through 8-hour work days in Indian humidity. Medium-to-full buildable coverage without looking cakey.",
    specs: {
      "Skin Type": "Oily, Combination",
      "Finish": "Matte",
      "Coverage": "Medium to Full",
      "Use": "Daily"
    },
    tags: ["foundation", "matte", "oily skin", "coverage", "makeup"],
    image: "/products/Maybelline-New.jpg",
    link: "https://amzn.to/4tCP38S",
  },
  {
    id: 20,
    name: "L'Oréal Paris Kajal Magique",
    brand: "L'Oréal Paris",
    category: "Makeup",
    subcat: "Kajal",
    mrp: 449,
    price: 269,
    rating: 4.1,
    reviews: "6.2k",
    asin: "B01BY5KDEC",
    badge: "Top Rated",
    description: "Intensely pigmented kajal that actually stays put in Indian heat and humidity. Smooth glide, waterproof formula, and 12-hour wear. One of the most consistently reviewed eye products in India for a reason.",
    specs: {
      "Type": "Kajal",
      "Finish": "Matte",
      "Waterproof": "Yes",
      "Longevity": "12 hours"
    },
    tags: ["kajal", "eyeliner", "smudge-proof", "waterproof", "eyes"],
    image: "/products/product-20.jpg",
    link: "https://amzn.to/4c9CAUn",
  },
  {
    id: 21,
    name: "WOW Skin Science Apple Cider Vinegar Shampoo",
    brand: "WOW Skin Science",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 374,
    price: 319,
    rating: 3.8,
    reviews: "45k",
    asin: "B09M8NN8DQ",
    badge: "Trending",
    description: "ACV shampoo that balances scalp pH, reduces dandruff, and clears product buildup. Sulphate-free and silicone-free. Especially effective during monsoon when oily scalp gets out of hand.",
    specs: {
      "Key Ingredient": "Apple Cider Vinegar",
      "Sulphate-Free": "Yes",
      "Silicone-Free": "Yes",
      "Best For": "Oily scalp, dandruff, buildup"
    },
    tags: ["shampoo", "apple cider vinegar", "scalp", "dandruff", "sulphate-free"],
    image: "/products/Wow-Skin.jpg",
    link: "https://amzn.to/4tCPAaS",
  },
  {
    id: 22,
    name: "Indulekha Bringha Hair Oil",
    brand: "Indulekha",
    category: "Hair Care",
    subcat: "Hair Oil",
    mrp: 999,
    price: 572,
    rating: 4.1,
    reviews: "74k",
    asin: "B086QDT64L",
    badge: "Ayurvedic Pick",
    description: "The ayurvedic hair oil with actual clinical backing. Bringharaj (eclipta alba) is one of the few traditional ingredients with published studies on hair growth. Loved by Indian grandmothers and dermatologists alike.",
    specs: {
      "Key Ingredient": "Bringharaj (Eclipta Alba)",
      "Type": "Hair Oil",
      "Best For": "Hair fall, scalp health, growth",
      "Ayurvedic": "Yes"
    },
    tags: ["hair oil", "bringha", "ayurvedic", "hair fall", "growth"],
    image: "/products/Indulekha-Bringha.jpg",
    link: "https://amzn.to/4t4zLd7",
  },
  {
    id: 23,
    name: "Dot & Key Vitamin C + E Super Bright Body Lotion",
    brand: "Dot & Key",
    category: "Body Care",
    subcat: "Body Lotion",
    mrp: 359,
    price: 316,
    rating: 4.2,
    reviews: "1.4k",
    asin: "B0CHJTCGS3",
    badge: "Glow Pick",
    description: "Lightweight body lotion with Vitamin C, E and Niacinamide that targets tan lines, uneven body tone, and dullness. All the concerns Indian skin deals with — especially on arms, legs, and neck.",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Vitamin C, Vitamin E, Niacinamide",
      "Best For": "Tan removal, brightening, uneven tone",
      "Fragrance": "Light"
    },
    tags: ["body lotion", "vitamin c", "brightening", "tan removal", "niacinamide"],
    image: "/products/Dot-Key-Vitamin.jpg",
    link: "https://amzn.to/4t7Wq8d",
  },
  {
    id: 24,
    name: "Vaseline Cocoa Radiant Body Lotion",
    brand: "Vaseline",
    category: "Body Care",
    subcat: "Body Lotion",
    mrp: 799,
    price: 720,
    rating: 4.2,
    reviews: "4.7k",
    asin: "B0059MUJR8",
    badge: "Best for Price",
    description: "No-nonsense daily body moisturiser with cocoa butter. Absorbs without greasiness, keeps dry skin comfortable through the day. One of the best-value body lotions in India.",
    specs: {
      "Skin Type": "Dry, Normal",
      "Key Ingredient": "Cocoa Butter, Petroleum Jelly",
      "Fragrance": "Light cocoa",
      "Use": "Daily"
    },
    tags: ["body lotion", "cocoa", "dry skin", "affordable", "moisturiser"],
    image: "/products/Vaseline-cream.jpg",
    link: "https://amzn.to/420LNs2",
  },
  {
    id: 25,
    name: "Himalaya Wellness Ashwagandha Tablets — 60 Tab",
    brand: "Himalaya",
    category: "Wellness",
    subcat: "Supplement",
    mrp: 228,
    price: 228,
    rating: 4.2,
    reviews: "40.3k",
    asin: "B01DQV8BIM",
    badge: "Adaptogen",
    description: "One of the most studied adaptogens for stress, cortisol regulation, and sleep quality. Relevant to skin too — chronic stress is a major driver of breakouts and dullness. Himalaya's standardised formulation is among the most trusted in India.",
    specs: {
      "Count": "60 Tablets",
      "Key Ingredient": "Ashwagandha Root Extract",
      "Dose": "1-2 tablets daily",
      "Vegetarian": "Yes"
    },
    tags: ["ashwagandha", "adaptogen", "wellness", "stress", "supplement", "ayurvedic"],
    image: "/products/Himalaya-Ashwagandha.jpg",
    link: "https://amzn.to/4td8ZPU",
  },
  {
    id: 26,
    name: "Himalaya Purifying Neem Face Wash 150ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 279,
    price: 205,
    rating: 4.4,
    reviews: "12.6k",
    asin: "B010Z0LH8I",
    badge: "Budget Pick",
    description: "Soap-free herbal neem and turmeric face wash that clears pimples and prevents acne. Natural antibacterial properties for oily and acne-prone skin.",
    specs: {
      "Skin Type": "All, Oily, Acne-Prone",
      "Key Ingredient": "Neem, Turmeric",
      "Texture": "Gel",
      "Use": "Daily"
    },
    tags: ["neem", "acne", "face wash", "himalaya"],
    image: "/products/Himalaya-Purifying.jpg",
    link: "https://amzn.to/4sOGsz7"
  },
  {
    id: 27,
    name: "Himalaya Neem Face Wash 100ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 199,
    price: 139,
    rating: 4.3,
    reviews: "7.8k",
    asin: "B002Q5JE2C",
    badge: "Value Deal",
    description: "Compact 100ml neem face wash with turmeric. Perfect for travel and daily use. Antibacterial and anti-inflammatory formula.",
    specs: {
      "Skin Type": "All, Oily, Combination",
      "Key Ingredient": "Neem, Turmeric",
      "Texture": "Gel",
      "Use": "Twice Daily"
    },
    tags: ["neem", "turmeric", "travel-size", "face wash"],
    image: "/products/Himalaya-Purifying-Neem.jpg",
    link: "https://amzn.to/3OOV6Z8"
  },
  {
    id: 28,
    name: "Himalaya Neem Face Wash 400ml Pack of 2",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 599,
    price: 599,
    rating: 4.3,
    reviews: "7k+",
    asin: "B0B5X5S8GY",
    badge: "Best Value",
    description: "Large 400ml bottle of Himalaya neem face wash with proven acne-fighting formula. Lasts months with daily use. Best for oily skin.",
    specs: {
      "Skin Type": "All, Oily, Acne-Prone",
      "Key Ingredient": "Neem, Turmeric",
      "Texture": "Gel",
      "Size": "400ml"
    },
    tags: ["neem", "large-size", "value", "acne"],
    image: "/products/Purifying-Neem-Face.jpg",
    link: "https://amzn.to/4ezkwV4"
  },

  {
    id: 29,
    name: "Himalaya Purifying Neem Foaming Face Wash, 150Ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 299,
    price: 190,
    rating: 4.3,
    reviews: "7k",
    asin: "B003OPE57C",
    badge: "Foaming Formula",
    description: "Foaming face wash with turmeric and neem. Creates a luxurious lather while gently cleansing. Soap-free formula suitable for all skin types.",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Turmeric, Neem",
      "Texture": "Foaming Gel",
      "Use": "Daily"
    },
    tags: ["foaming", "turmeric", "neem", "lather"],
    image: "/products/Himalaya-Purifying-Neem-Foaming.jpg",
    link: "https://amzn.to/4eFqaoy"
  },

  {
    id: 30,
    name: "Himalaya Brightening Vitamin C Orange Face Wash 100ml",
    brand: "Himalaya",
    category: "Skincare",
    subcat: "Face Wash",
    mrp: 209,
    price: 138,
    rating: 4.2,
    reviews: "700",
    asin: "B0CNTFMSWV",
    badge: "Brightening",
    description: "Vitamin C enriched face wash with orange extract. Brightens dull skin and removes tanning. Gentle enough for daily use.",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Vitamin C, Orange Extract",
      "Texture": "Gel",
      "Use": "Daily"
    },
    tags: ["vitamin-c", "brightening", "orange", "tan-removal"],
    image: "/products/Himalaya-Brightening-Vitamin-C.jpg",
    link: "https://amzn.to/3OCB9ES"
  },

  {
    id: 31,
    name: "The Ordinary Glycolic Acid 7% Exfoliating Toner 240ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Exfoliating Toner",
    mrp: 1275,
    price: 1275,
    rating: 4.4,
    reviews: "37k",
    asin: "B071914GGL",
    badge: "Exfoliating",
    description: "A 7% glycolic acid exfoliating toner for uneven texture, dullness and surface buildup. Use at night, start slowly, and follow with sunscreen the next morning.",
    specs: {
      "Skin Type": "Normal, Oily, Combination",
      "Key Ingredient": "Glycolic Acid 7%",
      "Texture": "Liquid",
      "Use": "PM only, 2-3x weekly"
    },
    tags: ["glycolic acid", "exfoliant", "dullness", "texture", "aha"],
    image: "/products/Ordinary-Glycolic -Acid-7.jpg",
    link: "https://amzn.to/41MA9Rt"
  },

  {
    id: 32,
    name: "The Ordinary Salicylic Acid 2% Solution 30ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Exfoliating Essence",
    mrp: 600,
    price: 599,
    rating: 4.1,
    reviews: "8.2k",
    asin: "B0C3PCJ6SD",
    badge: "Exfoliating",
    description: "Liquid exfoliant with 2% salicylic acid. Unclogs pores and reduces acne. Leave-on formula that works overnight for clear skin.",
    specs: {
      "Skin Type": "Oily, Acne-Prone, All",
      "Key Ingredient": "Salicylic Acid 2%",
      "Texture": "Liquid",
      "Use": "PM only"
    },
    tags: ["salicylic-acid", "exfoliant", "acne", "pores"],
    image: "/products/Ordinary-Salicylic- Acid.jpg",
    link: "https://amzn.to/4sQOxDx"
  },
  {
    id: 33,
    name: "The Ordinary Hyaluronic Acid 2% + B5 30ml",
    brand: "The Ordinary",
    category: "Skincare",
    subcat: "Hydrating Essence",
    mrp: 1000,
    price: 1000,
    rating: 4.6,
    reviews: "33k",
    asin: "B01MYEZPC8",
    badge: "Hydrating",
    description: "Lightweight hydrating serum with hyaluronic acid and panthenol. Plumps skin and maintains moisture. Works for all skin types.",
    specs: {
      "Skin Type": "All, Dry, Dehydrated",
      "Key Ingredient": "Hyaluronic Acid, B5",
      "Texture": "Liquid",
      "Use": "Daily"
    },
    tags: ["hyaluronic-acid", "panthenol", "hydration", "plumping"],
    image: "/products/Ordinary-Hyaluronic-Acid.jpg",
    link: "https://amzn.to/4mNmNyg"
  },
  {
    id: 34,
    name: "Plum Green Tea Face Toner 200ml",
    brand: "Plum",
    category: "Skincare",
    subcat: "Toner",
    mrp: 390,
    price: 378,
    rating: 4.2,
    reviews: "14k",
    asin: "B00OCJ5M6C",
    badge: "Green Tea",
    description: "Plum Green Tea Face Toner For Oily, Acne-Prone Skin | With Glycolic Acid | Alcohol-Free | Fights Pimples | Tightens Pores | Controls Oil | Gently Exfoliates Dead Skin Cells | Women & Men | 200ml.",
    specs: {
      "Skin Type": "Oily, Combination, Acne-Prone",
      "Key Ingredient": "Green Tea, Glycolic Acid",
      "Texture": "Liquid",
      "Use": "AM & PM"
    },
    tags: ["rice-water", "acne", "vegan", "clarifying"],
    image: "/products/Plum-Green-Tea.jpg",
    link: "https://amzn.to/48fE8d5"
  },
  {
    id: 35,
    name: "Plum 3% Niacinamide & Rice Water Face Toner 150ml",
    brand: "Plum",
    category: "Skincare",
    subcat: "Toner",
    mrp: 440,
    price: 449,
    rating: 4.2,
    reviews: "6.5k",
    asin: "B09PV4379W",
    badge: "Hydrating",
    description: "Alcohol-Free Toner for Oily Acne Prone Dry Combination Skin | Pore Tightening & Glowing Skin |Fades Blemishes, Brightens & Smoothens | Women & Men.",
    specs: {
      "Skin Type": "Dry, Dehydrated, All",
      "Key Ingredient": "Rice water, Niacinamide",
      "Texture": "Liquid",
      "Use": "Daily"
    },
    tags: ["rice-water", "Alcohol-Free", "hydration", "glow"],
    image: "/products/Plum-Niacinamide.jpg",
    link: "https://amzn.to/4u2JmB8"
  },
  {
    id: 36,
    name: "Minimalist Multi-Peptide Night Face Serum 30ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Essence",
    mrp: 699,
    price: 629,
    rating: 4.3,
    reviews: "3.8k",
    asin: "B08MVD6T8V",
    badge: "Anti-Ageing",
    description: "Peptide-rich serum that strengthens skin barrier and reduces wrinkles. Multi-peptide blend for comprehensive anti-aging benefits.",
    specs: {
      "Skin Type": "Mature, All Types",
      "Key Ingredient": "Multi-Peptide 10%",
      "Texture": "Serum",
      "Use": "AM & PM"
    },
    tags: ["peptide", "anti-aging", "barrier-repair", "wrinkles"],
    image: "/products/Minimalist-Multi-Peptide.jpg",
    link: "https://amzn.to/41R6Jlq"
  },
  {
    id: 37,
    name: "Dot & Key Watermelon 10% Glycolic Serum Exfoliating Essence 30ml",
    brand: "Dot & Key",
    category: "Skincare",
    subcat: "Exfoliating Essence",
    mrp: 599,
    price: 509,
    rating: 4.2,
    reviews: "300",
    asin: "B0BLRWFM22",
    badge: "Exfoliating",
    description: "Glycolic Serum for Face Glowing, With KojicI | Targets Pigmentation & Dark Spots | Targets Dullness, Uneven Texture, Sebum & Excess Oil | Serum For Oily & Normal Skin.",
    specs: {
      "Skin Type": "Normal, Oily, Combination",
      "Key Ingredient": "Glycolic Acid 8%",
      "Texture": "Liquid",
      "Use": "2-3x Weekly"
    },
    tags: ["glycolic-acid", "exfoliant", "brightening", "watermelon", "aha"],
    image: "/products/Dot-Key-Watermelon.jpg",
    link: "https://amzn.to/4tuB8BV"
  },
  {
    id: 38,
    name: "Mamaearth Onion Hair Oil 50ml",
    brand: "Mamaearth",
    category: "Hair Care",
    subcat: "Oil",
    mrp: 177,
    price: 171,
    rating: 4,
    reviews: "56k",
    asin: "B0CF61RF5B",
    badge: "Natural",
    description: "Onion Hair Oil for Hair Growth & Hair Fall Control with Redensyl .",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Onion Extract",
      "Texture": "Liquid",
      "Use": "Daily"
    },
    tags: ["onion", "brightening", "natural", "organic"],
    image: "/products/Mamaearth-Onion-Hair-Oil.jpg",
    link: "https://amzn.to/4cK4buo"
  },

  {
    id: 39,
    name: "L'Oréal True Match Foundation",
    brand: "L'Oréal",
    category: "Makeup",
    subcat: "Foundation",
    mrp: 2887,
    price: 1817,
    rating: 4.5,
    reviews: "620",
    asin: "B00112HQIU",
    badge: "SPF 17",
    description: "L'Oreal Paris True Match Super-Blendable Foundation, Natural Ivory, 1 fl. oz. Natural finish with lightweight coverage.",
    specs: {
      "Skin Type": "All",
      "Key Ingredient": "Titanium Dioxide, Glycerin",
      "Texture": "Liquid",
      "Use": "On face"
    },
    tags: ["glycerin", "foundation", "natural-finish", "spf"],
    image: "/products/True-Match.jpg",
    link: "https://amzn.to/4u9B8Y0"
  },
  {
    id: 40,
    name: "Maybelline New York Fit Me Concealer 25 Medium, 6.8ml",
    brand: "Maybelline",
    category: "Makeup",
    subcat: "Concealer",
    mrp: 599,
    price: 347,
    rating: 4.1,
    reviews: "2.1L+",
    asin: "B0046VGJJA",
    badge: "Daily Base",
    description: "Oil-free, fragrance-free concealer with natural matte coverage for under-eyes, blemishes, dark spots and quick everyday correction.",
    specs: {
      "Skin Type": "All, Normal, Oily, Combination",
      "Finish": "Natural Matte",
      "Coverage": "Medium to Full",
      "Use": "Under-eyes, dark spots, blemishes"
    },
    tags: ["concealer", "base makeup", "dark circles", "blemishes", "matte", "fragrance-free"],
    concerns: ["dark circles", "acne marks", "pigmentation", "oily skin"],
    bestFor: ["Everyday spot correction", "Under-eye brightening", "Normal to oily skin"],
    notIdealFor: ["Very dry under-eyes without prep", "Anyone needing a perfect shade match without testing first"],
    ingredients: ["Glycerin", "Titanium Dioxide", "Silica"],
    usage: "Dot a small amount on dark circles or marks, then tap with fingers, sponge or brush. Prep dry areas first.",
    watchOuts: ["Shade match matters more than hype. Check undertone before buying."],
    image: "/products/product-40.jpg",
    link: "https://www.amazon.in/dp/B0046VGJJA?tag=skinwithtanvi-21"
  },
  {
    id: 41,
    name: "Maybelline New York Fit Me Matte + Poreless Compact Powder 115 Ivory, 6g",
    brand: "Maybelline",
    category: "Makeup",
    subcat: "Compact Powder",
    mrp: 225,
    price: 129,
    rating: 4.2,
    reviews: "45.5k",
    asin: "B08QSQ8T7B",
    badge: "Oil Control",
    description: "Affordable pressed powder with a matte, pore-softening finish. Useful for touch-ups, T-zone oil control and setting light base makeup.",
    specs: {
      "Skin Type": "Normal, Oily",
      "Finish": "Matte",
      "Coverage": "Light to Medium",
      "Use": "Set base makeup, control shine"
    },
    tags: ["compact", "powder", "oil control", "matte", "base makeup", "spf"],
    concerns: ["oily skin", "shine", "base makeup"],
    bestFor: ["Oily T-zone touch-ups", "Budget everyday compact", "Setting concealer lightly"],
    notIdealFor: ["Very dry flaky skin", "Users needing high coverage foundation replacement"],
    ingredients: ["Clay", "UV Filters"],
    usage: "Press lightly on oily areas after sunscreen or base makeup. Avoid over-layering on dry patches.",
    watchOuts: ["Shade 115 is light. Pick a deeper shade if your skin tone needs it."],
    image: "/products/product-41.jpg",
    link: "https://www.amazon.in/dp/B08QSQ8T7B?tag=skinwithtanvi-21"
  },
  {
    id: 42,
    name: "Maybelline New York Lash Sensational Sky High Mascara Very Black, 6ml",
    brand: "Maybelline",
    category: "Makeup",
    subcat: "Mascara",
    mrp: 799,
    price: 479,
    rating: 4.2,
    reviews: "27.8k",
    asin: "B08H46YXYH",
    badge: "Lash Lift",
    description: "Lengthening and volumising mascara with a flexible brush for separated, lifted lashes. Strong pick when you want visible lashes without heavy eye makeup.",
    specs: {
      "Type": "Mascara",
      "Finish": "Very Black",
      "Waterproof": "Yes",
      "Use": "Lashes"
    },
    tags: ["mascara", "lashes", "waterproof", "lengthening", "volume", "eye makeup"],
    concerns: ["makeup", "eyes", "daily makeup"],
    bestFor: ["Lengthening lashes", "Minimal makeup days", "Humid weather wear"],
    notIdealFor: ["Users who dislike waterproof removal", "Very sensitive eyes without patch testing"],
    ingredients: ["Bamboo Extract", "Fibres"],
    usage: "Wiggle from lash root to tip. Remove with cleansing balm or micellar remover, not harsh rubbing.",
    watchOuts: ["Waterproof mascara needs proper removal to avoid lash breakage."],
    image: "/products/product-42.jpg",
    link: "https://www.amazon.in/dp/B08H46YXYH?tag=skinwithtanvi-21"
  },
  {
    id: 43,
    name: "Lakme 9 To 5 Primer + Matte Lip Color Blushing Nude, 3.6g",
    brand: "Lakme",
    category: "Makeup",
    subcat: "Lipstick",
    mrp: 650,
    price: 620,
    rating: 4.0,
    reviews: "1.7k",
    asin: "B076PV1SQM",
    badge: "Work Nude",
    description: "Primer-infused matte lipstick in a soft nude-pink shade. Good for office, minimal makeup and polished everyday looks.",
    specs: {
      "Finish": "Matte",
      "Shade": "Blushing Nude",
      "Texture": "Cream lipstick",
      "Use": "Lips"
    },
    tags: ["lipstick", "matte", "nude", "office makeup", "lakme", "lip color"],
    concerns: ["daily makeup", "lips", "office makeup"],
    bestFor: ["Soft nude-pink lip", "Workwear makeup", "Minimal base days"],
    notIdealFor: ["Very dry lips without lip balm", "Medium-deep skin tones if this shade washes you out"],
    usage: "Prep with lip balm, blot excess, then apply. Use a brown/nude liner if the shade looks too pale.",
    watchOuts: ["Customer feedback is mixed for medium to dusky tones, so shade suitability matters."],
    image: "/products/product-43.jpg",
    link: "https://www.amazon.in/dp/B076PV1SQM?tag=skinwithtanvi-21"
  },
  {
    id: 44,
    name: "Swiss Beauty Liquid Lightweight Concealer Warm-Sand, 6g",
    brand: "Swiss Beauty",
    category: "Makeup",
    subcat: "Concealer",
    mrp: 249,
    price: 199,
    rating: 4.2,
    reviews: "23.9k",
    asin: "B07WTNH18L",
    badge: "Budget Base",
    description: "Budget-friendly liquid concealer with lightweight, blendable coverage for dark circles, blemishes and pigmentation. Strong beginner pick.",
    specs: {
      "Skin Type": "All",
      "Finish": "Matte",
      "Coverage": "Medium to Full",
      "Use": "Conceal, correct, spot cover"
    },
    tags: ["concealer", "budget makeup", "dark circles", "pigmentation", "base makeup", "swiss beauty"],
    concerns: ["dark circles", "pigmentation", "acne marks", "budget makeup"],
    bestFor: ["Beginner-friendly concealer", "Budget full coverage", "Occasional makeup users"],
    notIdealFor: ["Exact shade matching without checking swatches", "Very dry under-eyes without moisturiser"],
    ingredients: ["Jojoba Seed Oil", "Hydrolyzed Collagen", "Iron Oxides"],
    usage: "Use a tiny amount and build coverage slowly. Blend fast with sponge, brush or fingers.",
    watchOuts: ["Affordable concealers can oxidise or look ashy if the undertone is wrong."],
    image: "/products/product-44.jpg",
    link: "https://www.amazon.in/dp/B07WTNH18L?tag=skinwithtanvi-21",
  },
  {
    id: 45,
    name: "Minimalist 10% Niacinamide + Zinc Serum — 30ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Serum",
    mrp: 599,
    price: 569,
    rating: 4.3,
    reviews: "18.5k",
    asin: "B08F9MF314",
    badge: "Best Overall",
    description: "10% Niacinamide + 1% Zinc PCA to control excess sebum and clear acne marks.",
    specs: {
      "Skin Type": "Oily, Combination, Normal",
      "Key Ingredient": "Niacinamide 10%, Zinc PCA 1%",
      "Texture": "Lightweight Fluid",
      "Use": "AM & PM"
    },
    tags: ["niacinamide", "serum", "oil control", "acne marks"],
    concerns: ["oily skin", "pigmentation"],
    image: "/products/Niacinamide-Serum.jpg",
    link: "https://www.amazon.in/dp/B08F9MF314?tag=skinwithtanvi-21"
  },
  {
    id: 46,
    name: "Minimalist 5% Niacinamide + Hyaluronic Acid Serum — 30ml",
    brand: "Minimalist",
    category: "Skincare",
    subcat: "Serum",
    mrp: 499,
    price: 474,
    rating: 4.2,
    reviews: "4.5k",
    asin: "B08KSGZ261",
    badge: "Best for Beginners",
    description: "5% Niacinamide combined with Hyaluronic Acid for gentle hydration and barrier repair.",
    specs: {
      "Skin Type": "Dry, Combination, Normal, Sensitive",
      "Key Ingredient": "Niacinamide 5%, Hyaluronic Acid",
      "Texture": "Lightweight Serum",
      "Use": "AM & PM"
    },
    tags: ["niacinamide", "serum", "hydration", "gentle"],
    concerns: ["dry skin", "pigmentation"],
    image: "/products/Minimalist-Vitamin.jpg",
    link: "https://www.amazon.in/dp/B08KSGZ261?tag=skinwithtanvi-21"
  },
  {
    id: 47,
    name: "Plum 10% Niacinamide Face Serum with Rice Water — 30ml",
    brand: "Plum",
    category: "Skincare",
    subcat: "Serum",
    mrp: 695,
    price: 590,
    rating: 4.2,
    reviews: "6.8k",
    asin: "B097R8B7J7",
    badge: "Rice Water",
    description: "10% Niacinamide with Rice Water to fade blemishes and brighten skin tone.",
    specs: {
      "Skin Type": "Oily, Combination, Normal",
      "Key Ingredient": "Niacinamide 10%, Rice Water Extract",
      "Texture": "Milky Liquid",
      "Use": "AM & PM"
    },
    tags: ["niacinamide", "serum", "rice water", "brightening"],
    concerns: ["pigmentation", "oily skin"],
    image: "/products/Plum-Niacinamide.jpg",
    link: "https://www.amazon.in/dp/B097R8B7J7?tag=skinwithtanvi-21"
  },
  {
    id: 48,
    name: "Mamaearth Skin Correct Face Serum with Niacinamide & Ginger — 30ml",
    brand: "Mamaearth",
    category: "Skincare",
    subcat: "Serum",
    mrp: 449,
    price: 381,
    rating: 4.0,
    reviews: "3k",
    asin: "B0848GX3P6",
    badge: "Ginger Extract",
    description: "Niacinamide and Ginger Extract to reduce acne marks, minimize pores, and soothe inflammation.",
    specs: {
      "Skin Type": "Oily, Acne-Prone, Normal",
      "Key Ingredient": "Niacinamide, Ginger Extract",
      "Texture": "Lightweight Fluid",
      "Use": "AM & PM"
    },
    tags: ["niacinamide", "serum", "acne marks", "pores"],
    concerns: ["acne", "pigmentation"],
    image: "/products/mamaearth_skin_correct.jpg",
    link: "https://www.amazon.in/dp/B0848GX3P6?tag=skinwithtanvi-21"
  },
  {
    id: 49,
    name: "Deconstruct 5% Niacinamide + Zinc + B5 Serum — 30ml",
    brand: "Deconstruct",
    category: "Skincare",
    subcat: "Serum",
    mrp: 449,
    price: 382,
    rating: 4.2,
    reviews: "3.2k",
    asin: "B08GG9M863",
    badge: "Best Budget Pick",
    description: "5% Niacinamide with Zinc PCA and Panthenol (B5) for gentle oil control and skin soothing.",
    specs: {
      "Skin Type": "Sensitive, Oily, Combination, Normal",
      "Key Ingredient": "Niacinamide 5%, Zinc, Panthenol",
      "Texture": "Watery Gel",
      "Use": "AM & PM"
    },
    tags: ["niacinamide", "serum", "gentle", "budget"],
    concerns: ["oily skin", "pigmentation"],
    image: "/products/deconstruct_niacinamide.jpg",
    link: "https://www.amazon.in/dp/B08GG9M863?tag=skinwithtanvi-21"
  },

  // ── Hard Water Shampoos ────────────────────────────────────────────────────
  {
    id: 50,
    name: "Detoxie Hard Water Repair Combo | Shampoo (200ml) + Conditioner (200ml)",
    brand: "Detoxie",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 599,
    price: 499,
    rating: 4.2,
    reviews: "3.4k",
    asin: "B0CLP4RRPC",
    badge: "Hard Water Combo",
    description: "India's most targeted hard water hair solution. Chelating shampoo + conditioner duo that removes calcium and magnesium mineral deposits from city tap water. Reduces hairfall, softens brittle strands, and repairs damage. Sulphate-free and safe for all hair types including children.",
    specs: {
      "Key Ingredient": "Chelating Agents, Amla, Bhringraj",
      "Sulphate-Free": "Yes",
      "Best For": "Hard water buildup, hairfall, brittle hair",
      "Pack": "Shampoo 200ml + Conditioner 200ml"
    },
    tags: ["hard water", "chelating shampoo", "hair fall", "mineral buildup", "detoxie", "combo"],
    concerns: ["hair fall", "hard water damage", "scalp health"],
    image: "/products/product-50.jpg",
    link: "https://amzn.to/3SfrSE5"
  },
  {
    id: 51,
    name: "Detoxie Power Cleanse Shampoo 150ml | Anti-Hairfall | Fights Hard Water",
    brand: "Detoxie",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 299,
    price: 249,
    rating: 4.1,
    reviews: "2.1k",
    asin: "B0H11ZXLMZ",
    badge: "Daily Use",
    description: "Daily-use detox shampoo for men and women. Fights sweat, pollution, and hard water buildup in one wash. Powered by Amla, Bhringraj, and Shikakai — classic Ayurvedic hair strengtheners paired with modern chelating actives. Reduces hairfall with consistent use.",
    specs: {
      "Key Ingredient": "Amla, Bhringraj, Shikakai",
      "Hair Type": "All Hair Types",
      "Size": "150ml",
      "Best For": "Daily cleanse, pollution + hard water defence"
    },
    tags: ["hard water", "daily shampoo", "detoxie", "amla", "bhringraj", "anti-hairfall", "men women"],
    concerns: ["hair fall", "hard water damage", "scalp health"],
    image: "/products/product-51.jpg",
    link: "https://amzn.to/4dZVe1K"
  },
  {
    id: 52,
    name: "L'Oréal Professionnel Serie Expert Metal DX Anti-Metal Cleansing Cream Shampoo",
    brand: "L'Oréal Professionnel",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 1490,
    price: 1320,
    rating: 4.3,
    reviews: "5.2k",
    asin: "B09B1FXGR3",
    badge: "Salon Grade",
    description: "Professional-grade chelating shampoo that neutralises metal particles — copper, iron, calcium — that hard water and pollution embed into hair. Leaves hair noticeably smoother after the first wash. Preferred by colour-treated hair users in hard water cities like Delhi and Mumbai.",
    specs: {
      "Key Ingredient": "Glicoamine (chelating), Citric Acid",
      "Hair Type": "All, especially colour-treated and damaged",
      "Best For": "Metal + mineral buildup, dull brittle hair"
    },
    tags: ["hard water", "metal detox", "chelating shampoo", "loreal professional", "salon", "colour-safe"],
    concerns: ["hard water damage", "dull hair", "chemical damage"],
    image: "/products/product-52.jpg",
    link: "https://amzn.to/4odVqOk"
  },
  {
    id: 53,
    name: "L'Oreal Paris Moisture Filling Shampoo with Hyaluronic Acid 650ml",
    brand: "L'Oréal Paris",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 599,
    price: 504,
    rating: 4.2,
    reviews: "8.6k",
    asin: "B0B6XTD8WW",
    badge: "Deep Hydration",
    description: "Hyaluronic acid shampoo that fills and seals dehydrated hair fibres — a direct result of hard water stripping moisture. Adds bounce, shine, and 72-hour hydration. Great follow-up to a weekly chelating shampoo for hard water users wanting soft, manageable hair.",
    specs: {
      "Key Ingredient": "Hyaluronic Acid",
      "Hair Type": "Dry, Dehydrated",
      "Size": "650ml",
      "Best For": "Moisture restoration after hard water damage"
    },
    tags: ["hard water", "hyaluronic acid", "loreal paris", "moisture", "dry hair", "bounce"],
    concerns: ["hard water damage", "dry hair", "dull hair"],
    image: "/products/product-53.jpg",
    link: "https://amzn.to/3RWb7xG"
  },
  {
    id: 54,
    name: "L'Oreal Paris Total Repair 5 Shampoo with Pro-Keratin + Ceramide 340ml",
    brand: "L'Oréal Paris",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 399,
    price: 283,
    rating: 4.3,
    reviews: "62.4k",
    asin: "B008KH31QU",
    badge: "Top Rated",
    description: "Targets 5 signs of hair damage: breakage, roughness, dullness, split ends, and dehydration — all of which are made worse by hard water. Pro-Keratin + Ceramide formula strengthens and smooths from root to tip. One of the best-reviewed shampoos on Amazon India.",
    specs: {
      "Key Ingredient": "Pro-Keratin, Ceramide",
      "Hair Type": "Damaged, Weak, Dry",
      "Size": "340ml",
      "Best For": "5-damage repair, hard water brittle hair"
    },
    tags: ["hard water", "keratin", "ceramide", "loreal paris", "repair", "damaged hair", "bestseller"],
    concerns: ["hard water damage", "brittle hair", "dull hair"],
    image: "/products/product-54.jpg",
    link: "https://amzn.to/43XM6os"
  },
  {
    id: 55,
    name: "Biotique Bio Soya Protein Fresh Nourishing Shampoo 340ml",
    brand: "Biotique",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 379,
    price: 319,
    rating: 4.1,
    reviews: "14.8k",
    asin: "B07YWM9WLX",
    badge: "pH Balanced",
    description: "Biotique's soya protein shampoo maintains scalp pH balance — important for countering the alkalinity of hard water. Repairs dry and damaged hair, adds shine, and prevents colour fading. Gentle enough for daily use with protein-infused cleansing.",
    specs: {
      "Key Ingredient": "Soya Protein, Dandelion Extract",
      "Hair Type": "All Hair Types",
      "Size": "340ml",
      "Best For": "pH balance, dry/damaged hair, colour protection"
    },
    tags: ["hard water", "ph balance", "biotique", "soya protein", "daily shampoo", "colour-safe"],
    concerns: ["hard water damage", "dry hair", "dull hair"],
    image: "/products/product-55.jpg",
    link: "https://amzn.to/4eejufm"
  },
  {
    id: 56,
    name: "Dove Intense Repair Shampoo 340ml",
    brand: "Dove",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 389,
    price: 324,
    rating: 4.3,
    reviews: "41.2k",
    asin: "B07HB2L7QD",
    badge: "Bestseller",
    description: "Dove's Keratin Repair Actives penetrate deep into hair fibres to reconstruct damage from hard water, heat, and chemical treatment. Strengthens and smooths dry, brittle hair. One of the most consistently reviewed repair shampoos on Amazon India at this price.",
    specs: {
      "Key Ingredient": "Keratin Repair Actives",
      "Hair Type": "Dry, Damaged",
      "Size": "340ml",
      "Best For": "Brittle, rough, hard-water-damaged hair"
    },
    tags: ["hard water", "dove", "damaged hair", "keratin", "repair", "strengthening"],
    concerns: ["hard water damage", "brittle hair", "dull hair"],
    image: "/products/product-56.jpg",
    link: "https://amzn.to/4fAlrVP"
  },
  {
    id: 57,
    name: "Dove Intense Repair Shampoo 1L",
    brand: "Dove",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 799,
    price: 685,
    rating: 4.3,
    reviews: "38.6k",
    asin: "B07H9SV624",
    badge: "Best Value",
    description: "Same Keratin Repair Actives formula as the 340ml but in a large 1L bottle — the smart buy for Indian households dealing with hard water daily. Repairs dry, damaged, and breakage-prone hair. Mild enough for men and women with frequent wash routines.",
    specs: {
      "Key Ingredient": "Keratin Repair Actives",
      "Hair Type": "Dry, Damaged",
      "Size": "1 Litre",
      "Best For": "Daily hard water use, value pack"
    },
    tags: ["hard water", "dove", "1 litre", "value", "damaged hair", "keratin", "repair"],
    concerns: ["hard water damage", "brittle hair", "dull hair"],
    image: "/products/product-57.jpg",
    link: "https://amzn.to/4orFvft"
  },
  {
    id: 58,
    name: "Schwarzkopf Professional Bonacure pH 4.5 Color Freeze Shampoo 250ml",
    brand: "Schwarzkopf Professional",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 1050,
    price: 900,
    rating: 4.2,
    reviews: "3.8k",
    asin: "B07CH18R7Y",
    badge: "pH Correcting",
    description: "Hard water is alkaline — it raises hair's pH and lifts cuticles, causing dryness and colour bleed. This Schwarzkopf pH 4.5 formula directly counteracts that by sealing the cuticle at its ideal acidic range. Best for colour-treated hair in high-TDS cities like Delhi, Gurugram, and Bengaluru.",
    specs: {
      "Key Ingredient": "pH 4.5 Active Repair, Citric Acid",
      "Hair Type": "Colour-treated, highlighted, grey",
      "Size": "250ml",
      "Best For": "pH correction, hard water brassiness, colour protection"
    },
    tags: ["hard water", "ph balancing", "schwarzkopf", "colour-treated", "brassiness", "salon"],
    concerns: ["hard water damage", "chemical damage", "dull hair"],
    image: "/products/product-58.jpg",
    link: "https://amzn.to/4e0q9v2"
  },
  {
    id: 59,
    name: "Schwarzkopf Professional Bonacure pH 4.5 Color Freeze Shampoo 1000ml",
    brand: "Schwarzkopf Professional",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 2100,
    price: 1700,
    rating: 4.3,
    reviews: "1.2k",
    asin: "B07C8Q99LM",
    badge: "Salon Size",
    description: "The professional 1000ml salon-size version of the Bonacure pH 4.5 Color Freeze shampoo. Ideal for salons and power users who wash frequently in hard water. Same cuticle-sealing, colour-preserving formula at better per-ml value.",
    specs: {
      "Key Ingredient": "pH 4.5 Active Repair, Citric Acid",
      "Hair Type": "Colour-treated, highlighted",
      "Size": "1000ml",
      "Best For": "Salon use, frequent washers in hard water areas"
    },
    tags: ["hard water", "ph balancing", "schwarzkopf", "colour-treated", "salon size", "1 litre"],
    concerns: ["hard water damage", "chemical damage", "dull hair"],
    image: "/products/product-59.jpg",
    link: "https://amzn.to/4ea3X07"
  },
  {
    id: 60,
    name: "Beauty of Joseon Relief Sun Rice + Probiotics 50 ml SPF 50+ PA++++",
    brand: "Beauty of Joseon",
    category: "Skincare",
    subcat: "Sunscreen",
    mrp: 1550,
    price: 1350,
    rating: 4.6,
    reviews: "15.2k",
    asin: "B09JVNZVH3",
    badge: "Korean SPF",
    description: "Lightweight Korean Sunscreen for Oily Skin. Uses organic chemical filters that leave zero white cast, perfect for brown skin. Enriched with rice extract and probiotics for a gentle, hydrating finish without feeling heavy in humidity.",
    specs: {
      "Skin Type": "Oily, Combination, Normal",
      "Key Ingredient": "Rice Extract 30%, Probiotics",
      "Use": "AM",
      "Finish": "Natural, No White Cast"
    },
    tags: ["sunscreen", "korean skincare", "spf 50", "no white cast", "beauty of joseon", "oily skin"],
    concerns: ["pigmentation", "sun protection"],
    image: "/products/product-60.jpg",
    link: "https://amzn.to/4oi7A92"
  },
  {
    id: 61,
    name: "The Face Shop Rice Water Bright Foaming Face Wash 100ml",
    brand: "The Face Shop",
    category: "Skincare",
    subcat: "Cleanser",
    mrp: 650,
    price: 600,
    rating: 4.4,
    reviews: "22.1k",
    asin: "B09P51T9FK",
    badge: "Brightening Wash",
    description: "Face Wash for Glowing Skin and uneven skin tone. A cult-favourite Korean cleanser that foams luxuriously to remove impurities without stripping the barrier. Ideal for oily and combination Indian skin.",
    specs: {
      "Skin Type": "Oily, Combination",
      "Key Ingredient": "Rice Water Extract, Soapwort",
      "Use": "AM & PM",
      "Format": "Foaming"
    },
    tags: ["cleanser", "face wash", "korean skincare", "the face shop", "rice water", "oily skin"],
    concerns: ["dullness", "uneven skin tone", "oiliness"],
    image: "/products/product-61.jpg",
    link: "https://amzn.to/4vDJ8RW"
  },
  {
    id: 62,
    name: "[Beauty of Joseon] Glow Deep Serum Rice + Arbutin (30ml)",
    brand: "Beauty of Joseon",
    category: "Skincare",
    subcat: "Serum",
    mrp: 1450,
    price: 1260,
    rating: 4.5,
    reviews: "8.3k",
    asin: "B09DLFCB69",
    badge: "For Pigmentation",
    description: "Korean Face Serum for Brightening, Even Skin Tone & Dark Spot Care. Features 68.6% Rice Bran Water and 2% Alpha Arbutin. A gentle but effective alternative to Vitamin C for fading pigmentation in the Indian summer.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Rice Bran Water, Alpha Arbutin 2%",
      "Use": "AM & PM",
      "Focus": "Brightening"
    },
    tags: ["serum", "pigmentation", "alpha arbutin", "beauty of joseon", "korean skincare", "brightening"],
    concerns: ["pigmentation", "dark spots", "dullness"],
    image: "/products/product-62.jpg",
    link: "https://amzn.to/4vBYjLi"
  },
  {
    id: 63,
    name: "The Face Shop Rice & Ceramide Face Cream 150ml",
    brand: "The Face Shop",
    category: "Skincare",
    subcat: "Moisturiser",
    mrp: 1100,
    price: 941,
    rating: 4.3,
    reviews: "12.4k",
    asin: "B07DSC6CWP",
    badge: "Barrier Repair",
    description: "Barrier Repair Moisturizer for Dry Skin, Intense Hydration & Strengthening. A rich, ceramide-packed K-beauty cream that provides a 12Hr Moisture Lock. Best used as a night cream or for dry skin types.",
    specs: {
      "Skin Type": "Dry, Normal",
      "Key Ingredient": "Ceramides, Rice Extract",
      "Use": "PM (or AM for Dry Skin)",
      "Texture": "Rich Cream"
    },
    tags: ["moisturiser", "ceramides", "barrier repair", "the face shop", "korean skincare", "dry skin"],
    concerns: ["dryness", "barrier damage"],
    image: "/products/product-63.jpg",
    link: "https://amzn.to/4v22eBn"
  },
  {
    id: 64,
    name: "Beauty of Joseon Glow Replenishing Rice Toner (150 Ml)",
    brand: "Beauty of Joseon",
    category: "Skincare",
    subcat: "Toner",
    mrp: 1500,
    price: 1350,
    rating: 4.7,
    reviews: "4.2k",
    asin: "B0D44T7RW9",
    badge: "Watery Hydration",
    description: "Hydrating & Balancing Facial Toner for Oily and Combination Skin. A watery, lightweight toner that absorbs instantly without stickiness. The perfect first step in an Indian summer K-beauty routine to control sebum and hydrate.",
    specs: {
      "Skin Type": "Oily, Combination",
      "Key Ingredient": "Rice Extract, Niacinamide",
      "Use": "AM & PM",
      "Texture": "Watery"
    },
    tags: ["toner", "hydration", "beauty of joseon", "korean skincare", "rice toner", "oily skin"],
    concerns: ["dehydration", "oiliness"],
    image: "/products/product-64.jpg",
    link: "https://amzn.to/4fvJzJe"
  },
  {
    id: 65,
    name: "SeoulCeuticals Korean Snail Mucin Serum – 97.5% Snail Serum",
    brand: "SeoulCeuticals",
    category: "Skincare",
    subcat: "Serum",
    mrp: 2800,
    price: 2450,
    rating: 4.5,
    reviews: "35k",
    asin: "B08XV3KZ84",
    badge: "Snail Mucin",
    description: "97.5% Snail Serum with Hyaluronic Acid & Centella. Anti Wrinkle & Anti Aging Serum for Face. A highly concentrated mucin formulation that deeply hydrates and repairs the skin barrier without feeling occlusive.",
    specs: {
      "Skin Type": "All Skin Types",
      "Key Ingredient": "Snail Mucin 97.5%, Centella, HA",
      "Use": "AM or PM",
      "Focus": "Repair & Hydration"
    },
    tags: ["serum", "snail mucin", "seoulceuticals", "korean skincare", "centella", "anti-aging"],
    concerns: ["barrier damage", "dehydration", "fine lines"],
    image: "/products/product-65.jpg",
    link: "https://amzn.to/3Q6C1T0"
  },
  {
    id: 1001,
    name: "Mulberry Silk Pillowcase — Both Sides 19 Momme Pure Silk",
    brand: "Pure Silk",
    category: "Lifestyle",
    subcat: "Bedding",
    mrp: 1499,
    price: 1299,
    rating: 4.4,
    reviews: "1.2k",
    asin: "B0F2T5FS7Q",
    badge: "Top Pick",
    description: "100% pure mulberry silk pillowcase on both sides. Reduces hair frizz, tangles, and breakage while sleeping. Extremely gentle on skin, preventing sleep lines and preserving skin hydration. Standard size.",
    specs: {
      "Material": "100% Mulberry Silk",
      "Momme": "19 Momme",
      "Size": "Standard",
      "Benefits": "Anti-frizz, anti-aging, hair & skin friendly"
    },
    tags: ["silk pillowcase", "pillowcase", "bedding", "hair care", "anti-aging"],
    image: "/products/silk_pillowcase.jpg",
    link: "https://www.amazon.in/dp/B0F2T5FS7Q?tag=skinwithtanvi-21"
  },
  {
    id: 1002,
    name: "Rose Quartz Gua Sha Facial Massage Tool",
    brand: "Pure Gems",
    category: "Skincare",
    subcat: "Facial Tool",
    mrp: 899,
    price: 599,
    rating: 4.3,
    reviews: "850",
    asin: "B0CPSK868C",
    badge: "Best Under ₹600",
    description: "100% natural rose quartz gua sha tool. Contoured edges designed for facial massage to promote lymphatic drainage, reduce under-eye puffiness, and relieve facial muscle tension.",
    specs: {
      "Material": "Natural Rose Quartz Stone",
      "Type": "Gua Sha Stone",
      "Usage": "Facial massage with oil/serum",
      "Benefits": "Depuffing, sculpting, tension relief"
    },
    tags: ["gua sha", "rose quartz", "facial tool", "massage", "depuffing"],
    image: "/products/gua_sha_set.jpg",
    link: "https://www.amazon.in/dp/B0CPSK868C?tag=skinwithtanvi-21"
  },
  {
    id: 1003,
    name: "L'Occitane Shea Butter Hand Cream — 30ml",
    brand: "L'Occitane",
    category: "Body Care",
    subcat: "Hand Cream",
    mrp: 1450,
    price: 1450,
    rating: 4.6,
    reviews: "15k",
    asin: "B002U0KUTE",
    badge: "Timeless Gift",
    description: "Award-winning hand cream formulated with 20% shea butter. Penetrates quickly to protect, nourish, and moisturize hands. Features a signature light, clean fragrance.",
    specs: {
      "Key Ingredient": "20% Shea Butter",
      "Size": "30ml",
      "Skin Type": "Dry to Very Dry",
      "Origin": "France"
    },
    tags: ["hand cream", "shea butter", "loccitane", "moisturiser", "luxury"],
    image: "/products/locitane_hand_cream.jpg",
    link: "https://www.amazon.in/dp/B002U0KUTE?tag=skinwithtanvi-21"
  },
  {
    id: 1004,
    name: "Bamboo Desk & Bedside Organiser Tray",
    brand: "EcoHome",
    category: "Lifestyle",
    subcat: "Organiser",
    mrp: 899,
    price: 649,
    rating: 4.4,
    reviews: "420",
    asin: "B0CG6CVRXR",
    badge: "Most Underrated",
    description: "Durable, moisture-resistant bamboo tray. Perfect for organizing daily essentials like keys, phone, watch, glasses, and daily skincare on your bedside table or office desk.",
    specs: {
      "Material": "Natural Bamboo",
      "Type": "Valet Tray",
      "Dimensions": "Standard Bedside Size",
      "Benefits": "Clutter-free desk, elegant storage"
    },
    tags: ["organiser", "bamboo tray", "desk organiser", "valet tray", "home decor"],
    image: "/products/bamboo_tray.jpg",
    link: "https://www.amazon.in/dp/B0CG6CVRXR?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1005,
    name: "Handheld Electric Milk Frother — Rechargeable",
    brand: "FrothMix",
    category: "Lifestyle",
    subcat: "Kitchen Tool",
    mrp: 799,
    price: 599,
    rating: 4.2,
    reviews: "2.1k",
    asin: "B0C8JC595G",
    badge: "Daily Use",
    description: "High-speed rechargeable electric milk frother. Creates rich, creamy foam for coffee, lattes, matcha, and protein shakes in under 20 seconds. Built-in rechargeable battery.",
    specs: {
      "Power Source": "USB Rechargeable",
      "Material": "Stainless Steel Wand",
      "Speed": "High speed motor",
      "Benefits": "Quick froth, café-quality drinks"
    },
    tags: ["milk frother", "frother", "kitchen tool", "coffee", "latte"],
    image: "/products/frother.jpg",
    link: "https://www.amazon.in/dp/B0C8JC595G?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1006,
    name: "Chalkboard Labels with White Chalk Marker — 45 Pack",
    brand: "LabelIt",
    category: "Lifestyle",
    subcat: "Organiser",
    mrp: 499,
    price: 349,
    rating: 4.5,
    reviews: "5.4k",
    asin: "B07Z3S4D58",
    badge: "Pantry Upgrade",
    description: "Waterproof, reusable chalkboard stickers for jar and container labeling. Easy to peel and restick. Comes with a white chalk marker that wipes clean with a damp cloth.",
    specs: {
      "Pack Count": "45 Labels",
      "Marker Included": "Yes (White Chalk)",
      "Reusable": "Yes (Wipe clean with damp cloth)",
      "Benefits": "Pantry organization, chalkboard look"
    },
    tags: ["labels", "chalkboard stickers", "pantry organiser", "kitchen labels"],
    image: "/products/chalkboard_labels.jpg",
    link: "https://www.amazon.in/dp/B07Z3S4D58?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1007,
    name: "Bala Bangles - Set of 2 (1lb Each) | Monochromatic Sea",
    brand: "Bala",
    category: "Wellness",
    subcat: "Fitness",
    mrp: 11125,
    price: 11125,
    rating: 4.6,
    reviews: "3.2k",
    asin: "B084Z1B84N",
    badge: "Aesthetic Toning",
    description: "Chic, premium wearable weights. Perfect for adding gentle resistance to pilates, walking, yoga, and home workouts. Made of steel wrapped in super-soft silicone.",
    specs: {
      "Weight": "1 Lb each (2 Lbs total)",
      "Material": "Steel wrapped in silicone",
      "Colors": "Monochromatic Sea",
      "Benefits": "Hands-free resistance, easy to clean"
    },
    tags: ["bala bangles", "ankle weights", "wrist weights", "pilates", "fitness", "wellness"],
    image: "/products/bala_bangles_sea.jpg",
    link: "https://amzn.to/4e4xfZa",
    hideFromShop: true
  },
  {
    id: 1008,
    name: "TYC - Trust Your Choice Natural Magnesium Oil Mist Spray",
    brand: "TYC",
    category: "Wellness",
    subcat: "Recovery",
    mrp: 302,
    price: 302,
    rating: 4.4,
    reviews: "950",
    asin: "B0D9M63K54",
    badge: "Recovery Essential",
    description: "Pure transdermal magnesium oil. Promotes deep muscle relaxation, reduces soreness, and supports restful sleep after low-impact exercise. Spray 4-5 times post-workout.",
    specs: {
      "Volume": "100ml",
      "Type": "Transdermal spray",
      "Ingredients": "Pure magnesium chloride",
      "Benefits": "Muscle recovery, cortisol regulation"
    },
    tags: ["magnesium spray", "magnesium oil", "muscle recovery", "sleep aid", "cortisol management"],
    image: "/products/tyc_magnesium.jpg",
    link: "https://amzn.to/43XbkTV",
    hideFromShop: true
  },
  {
    id: 1009,
    name: "Sirona Hypochlorous Acid Daily Skin Spray",
    brand: "Sirona",
    category: "Skincare",
    subcat: "Face Mist",
    mrp: 599,
    price: 399,
    rating: 4.3,
    reviews: "450",
    asin: "B0C9QW91K5",
    badge: "Gym Bag Essential",
    description: "Soothing, antibacterial facial mist. Formulated with hypochlorous acid to cleanse skin, reduce redness, and prevent gym sweat breakouts (acne mechanica) immediately after workouts.",
    specs: {
      "Volume": "80ml",
      "Active Ingredient": "Hypochlorous Acid",
      "Skin Type": "Acne-prone, sensitive",
      "Benefits": "Neutralizes bacteria, prevents gym acne"
    },
    tags: ["hypochlorous acid", "face spray", "gym skincare", "acne spray", "antibacterial mist"],
    image: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=600&q=80",
    link: "https://www.amazon.in/dp/B0C9QW91K5?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1011,
    name: "Solved Labs SOS Save Our Skin Hydrating Facial Toner",
    brand: "Solved Labs",
    category: "Skincare",
    subcat: "Face Mist",
    mrp: 349,
    price: 349,
    rating: 4.5,
    reviews: "120",
    asin: "B0CXSVYRYS",
    badge: "Gym Bag Essential",
    description: "Advanced hypochlorous acid facial mist. Instantly purifies skin, reduces redness, and defends against sweat-induced breakouts and acne mechanica.",
    specs: {
      "Volume": "100ml",
      "Active Ingredient": "0.02% Active Hypochlorous Acid",
      "Skin Type": "Acne-prone, sensitive, all skin types",
      "Benefits": "Antibacterial, hydrating, barrier support"
    },
    tags: ["solved labs", "sos spray", "hypochlorous acid", "face toner", "gym skincare", "acne toner"],
    image: "/products/solved_sos_spray.jpg",
    link: "https://amzn.to/4v4e1iA",
    hideFromShop: true
  },
  {
    id: 1010,
    name: "Boldfit High-Density Foam Roller for Posture & Back Stretch",
    brand: "Boldfit",
    category: "Wellness",
    subcat: "Posture",
    mrp: 999,
    price: 699,
    rating: 4.5,
    reviews: "6.2k",
    asin: "B0CKYY1M62",
    badge: "Posture Realign",
    description: "High-density EVA foam roller. Designed to release upper back tension, stretch tight chest muscles, and correct desk slouching posture. Includes online guides.",
    specs: {
      "Material": "High-density EVA foam",
      "Length": "18 inches",
      "Benefits": "Spinal decompression, chest opening",
      "Type": "Full round roller"
    },
    tags: ["foam roller", "posture correction", "back stretch", "thoracic mobility", "desk neck"],
    image: "/products/boldfit_foam_roller.jpg",
    link: "https://amzn.to/3QxtBEg",
    hideFromShop: true
  },
  {
    id: 1011,
    name: "Minimalist Anti-Dandruff Shampoo",
    brand: "Minimalist",
    category: "Hair Care",
    subcat: "Shampoo",
    mrp: 349,
    price: 299,
    rating: 4.1,
    reviews: "2.1k",
    asin: "B0DT76HL84",
    badge: "Anti-Dandruff",
    description: "Sulphate-free and fragrance-free clarifying shampoo with 1% Salicylic Acid and 0.5% Climbazole to treat dandruff and relieve scalp itchiness.",
    specs: {
      "Hair Type": "All Hair Types",
      "Key Ingredient": "Salicylic Acid, Climbazole",
      "Texture": "Liquid Gel",
      "Use": "2-3 times weekly"
    },
    tags: ["shampoo", "anti-dandruff", "dandruff", "minimalist", "salicylic acid"],
    image: "/products/minimalist-dandruff.jpg",
    link: "https://www.amazon.in/dp/B0DT76HL84?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1012,
    name: "Coco Soul Hairfall Control Conditioner",
    brand: "Coco Soul",
    category: "Hair Care",
    subcat: "Conditioner",
    mrp: 499,
    price: 399,
    rating: 4.0,
    reviews: "1.2k",
    asin: "B0BGKX6Z45",
    badge: "Organic Coco",
    description: "Formulated with 100% organic virgin coconut oil and ayurvedic herbs to reduce hair breakage and deeply condition lengths.",
    specs: {
      "Hair Type": "Dry, Damaged, Frizzy",
      "Key Ingredient": "Organic Coconut Oil, Onion",
      "Texture": "Cream",
      "Use": "After every shampoo wash"
    },
    tags: ["conditioner", "hairfall control", "coco soul", "organic coconut oil"],
    image: "/products/cocosoul-conditioner.jpg",
    link: "https://www.amazon.in/dp/B0BGKX6Z45?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1013,
    name: "Minimalist Maleic Bond Repair Complex 05% Hair Mask",
    brand: "Minimalist",
    category: "Hair Care",
    subcat: "Hair Mask",
    mrp: 699,
    price: 649,
    rating: 4.3,
    reviews: "3.5k",
    asin: "B0FWKGNZRJ",
    badge: "Bond Repair",
    description: "Patent-pending bond repair complex containing 5% Maleic Acid, Transglutaminase, and Ceramides to rebuild broken disulfide bonds and repair damaged hair.",
    specs: {
      "Hair Type": "Damaged, Treated, Dry",
      "Key Ingredient": "Maleic Acid, Ceramides",
      "Texture": "Thick Cream",
      "Use": "Once weekly (leave on for 15 mins)"
    },
    tags: ["hair mask", "bond repair", "minimalist", "maleic acid"],
    image: "/products/minimalist-bond-repair.jpg",
    link: "https://www.amazon.in/dp/B0FWKGNZRJ?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1014,
    name: "WOW Skin Science Onion Black Seed Hair Oil",
    brand: "WOW Skin Science",
    category: "Hair Care",
    subcat: "Hair Oil",
    mrp: 399,
    price: 349,
    rating: 4.0,
    reviews: "54k",
    asin: "B07NDR2J4K",
    badge: "Hairfall Control",
    description: "Powered by onion black seed oil blended with sweet almond, castor, jojoba, olive, and coconut oils to control hair fall and promote growth.",
    specs: {
      "Hair Type": "All Hair Types, Thinning",
      "Key Ingredient": "Onion Black Seed Oil",
      "Texture": "Non-greasy Oil",
      "Use": "Pre-wash treatment"
    },
    tags: ["hair oil", "wow", "onion oil", "black seed oil"],
    image: "/products/wow-onion-oil.jpg",
    link: "https://www.amazon.in/dp/B07NDR2J4K?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1015,
    name: "WOW Skin Science Moroccan Argan Hair Oil",
    brand: "WOW Skin Science",
    category: "Hair Care",
    subcat: "Hair Oil",
    mrp: 399,
    price: 349,
    rating: 4.1,
    reviews: "12k",
    asin: "B07P7N1YM2",
    badge: "Argan Shine",
    description: "Premium hair oil with cold-pressed Moroccan Argan Oil to restore shine, reduce dryness, and protect hair from styling heat.",
    specs: {
      "Hair Type": "Dry, Frizzy, Dull",
      "Key Ingredient": "Moroccan Argan Oil",
      "Texture": "Lightweight Oil",
      "Use": "Leave-in or overnight treatment"
    },
    tags: ["hair oil", "argan oil", "wow", "moroccan argan"],
    image: "/products/wow-argan-oil.jpg",
    link: "https://www.amazon.in/dp/B07P7N1YM2?tag=skinwithtanvi-21",
    hideFromShop: true
  },
  {
    id: 1016,
    name: "Minimalist Hair Growth Actives 18% Hair Density Serum",
    brand: "Minimalist",
    category: "Hair Care",
    subcat: "Hair Serum",
    mrp: 799,
    price: 759,
    rating: 4.2,
    reviews: "15k",
    asin: "B093LMJFVH",
    badge: "Hair Growth",
    description: "Supercharged hair serum formulated with 18% concentrations of Redensyl, Procapil, Capixyl, Baicapil, and Anagain to reduce hair fall and boost thickness.",
    specs: {
      "Hair Type": "Thinning, Hair Fall Prone",
      "Key Ingredient": "Redensyl 3%, Procapil 3%",
      "Texture": "Watery Serum",
      "Use": "Daily PM leave-on scalp serum"
    },
    tags: ["hair serum", "hair growth", "redensyl", "minimalist"],
    image: "/products/minimalist-growth-serum.jpg",
    link: "https://www.amazon.in/dp/B093LMJFVH?tag=skinwithtanvi-21",
    hideFromShop: true
  }
];


export function getProductAffiliateUrl(product: any, countryCode?: string): string {
  // [TEMPORARILY DISABLED] International Awin links are on hold pending Payoneer setup.
  // Defaulting all worldwide traffic to local Amazon IN links for now.
  /*
  let isGlobal = false;
  if (countryCode) {
    isGlobal = countryCode.toUpperCase() !== 'IN';
  } else if (typeof window !== 'undefined') {
    try {
      const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
      isGlobal = tz !== 'Asia/Kolkata' && tz !== 'Asia/Calcutta';
    } catch (e) {
      isGlobal = false;
    }
  }

  if (isGlobal && product.cultBeautyLink) {
    const awinPublisherId = process.env.NEXT_PUBLIC_AWIN_PUBLISHER_ID;
    // Only wrap in Awin redirect if a valid Publisher ID is provided.
    // If not set, route directly to the Cult Beauty product page to prevent any 404 or tracking errors.
    if (awinPublisherId && awinPublisherId !== 'YOUR_AWIN_ID' && awinPublisherId.trim() !== '') {
      return `https://www.awin1.com/cread.php?awinmid=29063&awinaffid=${awinPublisherId}&ued=${encodeURIComponent(product.cultBeautyLink)}`;
    }
    return product.cultBeautyLink;
  }
  */

  return product.link || `https://www.amazon.in/dp/${product.asin}?tag=skinwithtanvi-21`;
}
